
#line 3 "lex.yy.c"

#define  YY_INT_ALIGNED short int

/* A lexical scanner generated by flex */

#define FLEX_SCANNER
#define YY_FLEX_MAJOR_VERSION 2
#define YY_FLEX_MINOR_VERSION 6
#define YY_FLEX_SUBMINOR_VERSION 0
#if YY_FLEX_SUBMINOR_VERSION > 0
#define FLEX_BETA
#endif

/* First, we deal with  platform-specific or compiler-specific issues. */

/* begin standard C headers. */
#include <stdio.h>
#include <string.h>
#include <errno.h>
#include <stdlib.h>

/* end standard C headers. */

/* flex integer type definitions */

#ifndef FLEXINT_H
#define FLEXINT_H

/* C99 systems have <inttypes.h>. Non-C99 systems may or may not. */

#if defined (__STDC_VERSION__) && __STDC_VERSION__ >= 199901L

/* C99 says to define __STDC_LIMIT_MACROS before including stdint.h,
 * if you want the limit (max/min) macros for int types. 
 */
#ifndef __STDC_LIMIT_MACROS
#define __STDC_LIMIT_MACROS 1
#endif

#include <inttypes.h>
typedef int8_t flex_int8_t;
typedef uint8_t flex_uint8_t;
typedef int16_t flex_int16_t;
typedef uint16_t flex_uint16_t;
typedef int32_t flex_int32_t;
typedef uint32_t flex_uint32_t;
#else
typedef signed char flex_int8_t;
typedef short int flex_int16_t;
typedef int flex_int32_t;
typedef unsigned char flex_uint8_t; 
typedef unsigned short int flex_uint16_t;
typedef unsigned int flex_uint32_t;

/* Limits of integral types. */
#ifndef INT8_MIN
#define INT8_MIN               (-128)
#endif
#ifndef INT16_MIN
#define INT16_MIN              (-32767-1)
#endif
#ifndef INT32_MIN
#define INT32_MIN              (-2147483647-1)
#endif
#ifndef INT8_MAX
#define INT8_MAX               (127)
#endif
#ifndef INT16_MAX
#define INT16_MAX              (32767)
#endif
#ifndef INT32_MAX
#define INT32_MAX              (2147483647)
#endif
#ifndef UINT8_MAX
#define UINT8_MAX              (255U)
#endif
#ifndef UINT16_MAX
#define UINT16_MAX             (65535U)
#endif
#ifndef UINT32_MAX
#define UINT32_MAX             (4294967295U)
#endif

#endif /* ! C99 */

#endif /* ! FLEXINT_H */

#ifdef __cplusplus

/* The "const" storage-class-modifier is valid. */
#define YY_USE_CONST

#else	/* ! __cplusplus */

/* C99 requires __STDC__ to be defined as 1. */
#if defined (__STDC__)

#define YY_USE_CONST

#endif	/* defined (__STDC__) */
#endif	/* ! __cplusplus */

#ifdef YY_USE_CONST
#define yyconst const
#else
#define yyconst
#endif

/* Returned upon end-of-file. */
#define YY_NULL 0

/* Promotes a possibly negative, possibly signed char to an unsigned
 * integer for use as an array index.  If the signed char is negative,
 * we want to instead treat it as an 8-bit unsigned char, hence the
 * double cast.
 */
#define YY_SC_TO_UI(c) ((unsigned int) (unsigned char) c)

/* Enter a start condition.  This macro really ought to take a parameter,
 * but we do it the disgusting crufty way forced on us by the ()-less
 * definition of BEGIN.
 */
#define BEGIN (yy_start) = 1 + 2 *

/* Translate the current start state into a value that can be later handed
 * to BEGIN to return to the state.  The YYSTATE alias is for lex
 * compatibility.
 */
#define YY_START (((yy_start) - 1) / 2)
#define YYSTATE YY_START

/* Action number for EOF rule of a given start state. */
#define YY_STATE_EOF(state) (YY_END_OF_BUFFER + state + 1)

/* Special action meaning "start processing a new file". */
#define YY_NEW_FILE yyrestart(yyin  )

#define YY_END_OF_BUFFER_CHAR 0

/* Size of default input buffer. */
#ifndef YY_BUF_SIZE
#ifdef __ia64__
/* On IA-64, the buffer size is 16k, not 8k.
 * Moreover, YY_BUF_SIZE is 2*YY_READ_BUF_SIZE in the general case.
 * Ditto for the __ia64__ case accordingly.
 */
#define YY_BUF_SIZE 32768
#else
#define YY_BUF_SIZE 16384
#endif /* __ia64__ */
#endif

/* The state buf must be large enough to hold one state per character in the main buffer.
 */
#define YY_STATE_BUF_SIZE   ((YY_BUF_SIZE + 2) * sizeof(yy_state_type))

#ifndef YY_TYPEDEF_YY_BUFFER_STATE
#define YY_TYPEDEF_YY_BUFFER_STATE
typedef struct yy_buffer_state *YY_BUFFER_STATE;
#endif

#ifndef YY_TYPEDEF_YY_SIZE_T
#define YY_TYPEDEF_YY_SIZE_T
typedef size_t yy_size_t;
#endif

extern yy_size_t yyleng;

extern FILE *yyin, *yyout;

#define EOB_ACT_CONTINUE_SCAN 0
#define EOB_ACT_END_OF_FILE 1
#define EOB_ACT_LAST_MATCH 2

    #define YY_LESS_LINENO(n)
    #define YY_LINENO_REWIND_TO(ptr)
    
/* Return all but the first "n" matched characters back to the input stream. */
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
        int yyless_macro_arg = (n); \
        YY_LESS_LINENO(yyless_macro_arg);\
		*yy_cp = (yy_hold_char); \
		YY_RESTORE_YY_MORE_OFFSET \
		(yy_c_buf_p) = yy_cp = yy_bp + yyless_macro_arg - YY_MORE_ADJ; \
		YY_DO_BEFORE_ACTION; /* set up yytext again */ \
		} \
	while ( 0 )

#define unput(c) yyunput( c, (yytext_ptr)  )

#ifndef YY_STRUCT_YY_BUFFER_STATE
#define YY_STRUCT_YY_BUFFER_STATE
struct yy_buffer_state
	{
	FILE *yy_input_file;

	char *yy_ch_buf;		/* input buffer */
	char *yy_buf_pos;		/* current position in input buffer */

	/* Size of input buffer in bytes, not including room for EOB
	 * characters.
	 */
	yy_size_t yy_buf_size;

	/* Number of characters read into yy_ch_buf, not including EOB
	 * characters.
	 */
	int yy_n_chars;

	/* Whether we "own" the buffer - i.e., we know we created it,
	 * and can realloc() it to grow it, and should free() it to
	 * delete it.
	 */
	int yy_is_our_buffer;

	/* Whether this is an "interactive" input source; if so, and
	 * if we're using stdio for input, then we want to use getc()
	 * instead of fread(), to make sure we stop fetching input after
	 * each newline.
	 */
	int yy_is_interactive;

	/* Whether we're considered to be at the beginning of a line.
	 * If so, '^' rules will be active on the next match, otherwise
	 * not.
	 */
	int yy_at_bol;

    int yy_bs_lineno; /**< The line count. */
    int yy_bs_column; /**< The column count. */
    
	/* Whether to try to fill the input buffer when we reach the
	 * end of it.
	 */
	int yy_fill_buffer;

	int yy_buffer_status;

#define YY_BUFFER_NEW 0
#define YY_BUFFER_NORMAL 1
	/* When an EOF's been seen but there's still some text to process
	 * then we mark the buffer as YY_EOF_PENDING, to indicate that we
	 * shouldn't try reading from the input source any more.  We might
	 * still have a bunch of tokens to match, though, because of
	 * possible backing-up.
	 *
	 * When we actually see the EOF, we change the status to "new"
	 * (via yyrestart()), so that the user can continue scanning by
	 * just pointing yyin at a new input file.
	 */
#define YY_BUFFER_EOF_PENDING 2

	};
#endif /* !YY_STRUCT_YY_BUFFER_STATE */

/* Stack of input buffers. */
static size_t yy_buffer_stack_top = 0; /**< index of top of stack. */
static size_t yy_buffer_stack_max = 0; /**< capacity of stack. */
static YY_BUFFER_STATE * yy_buffer_stack = 0; /**< Stack as an array. */

/* We provide macros for accessing buffer states in case in the
 * future we want to put the buffer states in a more general
 * "scanner state".
 *
 * Returns the top of the stack, or NULL.
 */
#define YY_CURRENT_BUFFER ( (yy_buffer_stack) \
                          ? (yy_buffer_stack)[(yy_buffer_stack_top)] \
                          : NULL)

/* Same as previous macro, but useful when we know that the buffer stack is not
 * NULL or when we need an lvalue. For internal use only.
 */
#define YY_CURRENT_BUFFER_LVALUE (yy_buffer_stack)[(yy_buffer_stack_top)]

/* yy_hold_char holds the character lost when yytext is formed. */
static char yy_hold_char;
static int yy_n_chars;		/* number of characters read into yy_ch_buf */
yy_size_t yyleng;

/* Points to current character in buffer. */
static char *yy_c_buf_p = (char *) 0;
static int yy_init = 0;		/* whether we need to initialize */
static int yy_start = 0;	/* start state number */

/* Flag which is used to allow yywrap()'s to do buffer switches
 * instead of setting up a fresh yyin.  A bit of a hack ...
 */
static int yy_did_buffer_switch_on_eof;

void yyrestart (FILE *input_file  );
void yy_switch_to_buffer (YY_BUFFER_STATE new_buffer  );
YY_BUFFER_STATE yy_create_buffer (FILE *file,int size  );
void yy_delete_buffer (YY_BUFFER_STATE b  );
void yy_flush_buffer (YY_BUFFER_STATE b  );
void yypush_buffer_state (YY_BUFFER_STATE new_buffer  );
void yypop_buffer_state (void );

static void yyensure_buffer_stack (void );
static void yy_load_buffer_state (void );
static void yy_init_buffer (YY_BUFFER_STATE b,FILE *file  );

#define YY_FLUSH_BUFFER yy_flush_buffer(YY_CURRENT_BUFFER )

YY_BUFFER_STATE yy_scan_buffer (char *base,yy_size_t size  );
YY_BUFFER_STATE yy_scan_string (yyconst char *yy_str  );
YY_BUFFER_STATE yy_scan_bytes (yyconst char *bytes,yy_size_t len  );

void *yyalloc (yy_size_t  );
void *yyrealloc (void *,yy_size_t  );
void yyfree (void *  );

#define yy_new_buffer yy_create_buffer

#define yy_set_interactive(is_interactive) \
	{ \
	if ( ! YY_CURRENT_BUFFER ){ \
        yyensure_buffer_stack (); \
		YY_CURRENT_BUFFER_LVALUE =    \
            yy_create_buffer(yyin,YY_BUF_SIZE ); \
	} \
	YY_CURRENT_BUFFER_LVALUE->yy_is_interactive = is_interactive; \
	}

#define yy_set_bol(at_bol) \
	{ \
	if ( ! YY_CURRENT_BUFFER ){\
        yyensure_buffer_stack (); \
		YY_CURRENT_BUFFER_LVALUE =    \
            yy_create_buffer(yyin,YY_BUF_SIZE ); \
	} \
	YY_CURRENT_BUFFER_LVALUE->yy_at_bol = at_bol; \
	}

#define YY_AT_BOL() (YY_CURRENT_BUFFER_LVALUE->yy_at_bol)

/* Begin user sect3 */

typedef unsigned char YY_CHAR;

FILE *yyin = (FILE *) 0, *yyout = (FILE *) 0;

typedef int yy_state_type;

extern int yylineno;

int yylineno = 1;

extern char *yytext;
#ifdef yytext_ptr
#undef yytext_ptr
#endif
#define yytext_ptr yytext

static yy_state_type yy_get_previous_state (void );
static yy_state_type yy_try_NUL_trans (yy_state_type current_state  );
static int yy_get_next_buffer (void );
#if defined(__GNUC__) && __GNUC__ >= 3
__attribute__((__noreturn__))
#endif
static void yy_fatal_error (yyconst char msg[]  );

/* Done after the current pattern has been matched and before the
 * corresponding action - sets up yytext.
 */
#define YY_DO_BEFORE_ACTION \
	(yytext_ptr) = yy_bp; \
	yyleng = (size_t) (yy_cp - yy_bp); \
	(yy_hold_char) = *yy_cp; \
	*yy_cp = '\0'; \
	(yy_c_buf_p) = yy_cp;

#define YY_NUM_RULES 155
#define YY_END_OF_BUFFER 156
/* This struct is not used in this scanner,
   but its presence is necessary. */
struct yy_trans_info
	{
	flex_int32_t yy_verify;
	flex_int32_t yy_nxt;
	};
static yyconst flex_int16_t yy_accept[548] =
    {   0,
        0,    0,  156,  155,    2,    1,  141,  155,  155,  154,
      147,  140,  155,  136,  137,  145,  144,  133,  143,  107,
      146,  100,  100,  134,  130,  148,  135,  149,  152,  153,
       96,  138,  139,  150,   96,   96,   96,   96,   96,   96,
       96,   96,   96,   96,   96,   96,   96,   96,   96,   96,
       96,   96,   96,   96,  131,  151,  132,  142,    2,  128,
        0,  105,    0,    0,  154,  114,  123,  115,    0,    0,
      112,  120,  110,  121,  111,  122,  103,    0,    3,  113,
      104,   99,  100,    0,  100,    0,    0,  129,  119,  125,
      127,  126,  118,   96,  116,   96,   96,   96,   96,   96,

       96,   96,   96,   96,   96,   96,   96,   96,   29,   96,
       96,   96,   96,   96,   96,   96,   96,   96,   42,   96,
       96,   96,   96,   96,   96,   96,   96,   54,   96,   96,
       96,   96,   96,   96,   96,   96,   96,   96,   96,   96,
       96,   96,   96,   96,   96,   96,  117,  124,    0,  101,
        0,  103,    0,    0,    3,  103,    0,  104,   99,    0,
      102,   98,   97,  109,  108,   96,   96,    5,    9,   96,
       96,   96,   96,   96,   96,   96,   96,   96,   96,   96,
       96,   96,   96,   96,   96,   96,   96,   96,   96,   96,
       39,   96,   96,   96,   44,   96,   96,   96,   48,   96,

       50,   96,   96,   96,   96,   96,   96,   96,   96,   96,
       96,   96,   96,   96,   95,   96,   96,   96,   96,   96,
       96,   75,   96,   96,   96,   96,   96,   96,   96,   96,
       96,   87,    0,    0,  103,    0,    3,    0,  103,    0,
      104,  102,   98,   97,   96,   96,   96,   10,   96,   96,
       13,   96,   15,   96,   17,   96,   96,   96,   96,   96,
       96,   96,   96,   96,   32,   33,   96,   96,   96,   96,
       96,   96,   41,   96,   45,   96,   96,   96,   96,   96,
       96,   96,   96,   96,   96,   96,   96,   96,   96,   96,
       96,   96,   96,   96,   96,   71,   96,   96,   74,   96,

       96,   96,   96,   96,   83,   96,   96,   96,   96,    0,
        0,  103,    4,   96,   96,   96,   12,   14,   16,   96,
       96,   20,   21,   22,   96,   96,   96,   96,   96,   96,
       96,   96,   96,   37,   38,   96,   96,   96,   96,   96,
       96,   96,   96,   55,   96,   96,   96,   96,   96,   96,
       62,   96,   96,   96,   96,   96,   96,   96,   73,   96,
       96,   96,   79,   96,   81,   96,   96,   96,   86,   96,
        0,   96,   96,    6,   11,   96,   96,   96,   96,   96,
       96,   96,   28,   30,   96,   96,   35,   36,   40,   43,
       96,   96,   96,   51,   96,   96,   96,   96,   58,   96,

       96,   61,   63,   64,   65,   68,   69,   96,   96,   96,
       77,   96,   96,   96,   96,   96,   88,    0,    7,    8,
       96,   96,   96,   96,   96,   96,   27,   96,   96,   46,
       96,   96,   52,   96,   56,   96,   96,   96,   96,   96,
       96,   76,   96,   96,   82,   96,   85,    0,   18,   19,
       96,   96,   25,   26,   96,   34,   96,   49,   53,   96,
       59,   96,   96,   96,   70,   96,   78,   80,   84,    0,
        0,   96,   23,   96,   47,   57,   96,   96,   96,   96,
        0,    0,    0,   24,   96,   96,   96,   96,   96,    0,
        0,    0,    0,  106,   96,   96,   96,   67,   96,    0,

        0,    0,    0,    0,    0,   31,   96,   96,   72,    0,
        0,    0,    0,    0,    0,   96,   66,    0,    0,    0,
        0,    0,    0,   96,    0,    0,    0,    0,    0,    0,
       96,   93,    0,   91,    0,    0,    0,   60,    0,    0,
        0,   90,   92,   94,    0,   89,    0
    } ;

static yyconst YY_CHAR yy_ec[256] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    2,    3,
        1,    2,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    4,    5,    6,    7,    8,    9,   10,   11,   12,
       13,   14,   15,   16,   17,   18,   19,   20,   21,   22,
       23,   24,   24,   25,   24,   26,   26,   27,   28,   29,
       30,   31,   32,   33,   34,   34,   34,   34,   35,   36,
       37,   37,   37,   37,   37,   38,   37,   37,   37,   37,
       37,   37,   37,   37,   39,   37,   37,   40,   37,   37,
       41,   42,   43,   44,   45,    1,   46,   47,   48,   49,

       50,   51,   52,   53,   54,   37,   55,   56,   57,   58,
       59,   60,   61,   62,   63,   64,   65,   66,   67,   68,
       69,   70,   71,   72,   73,   74,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,

        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1
    } ;

static yyconst YY_CHAR yy_meta[75] =
    {   0,
        1,    1,    2,    1,    1,    3,    1,    1,    1,    1,
        4,    1,    1,    1,    1,    1,    1,    1,    1,    5,
        5,    5,    5,    5,    5,    5,    1,    1,    1,    1,
        1,    1,    1,    5,    5,    5,    6,    6,    6,    6,
        1,    3,    1,    1,    6,    5,    5,    5,    5,    5,
        5,    6,    6,    6,    6,    6,    6,    6,    6,    6,
        6,    6,    6,    6,    6,    6,    6,    6,    6,    6,
        1,    1,    1,    1
    } ;

static yyconst flex_uint16_t yy_base[555] =
    {   0,
        0,    0,  771,  772,   73,  772,  740,   70,  715,  760,
      737,   68,  724,  772,  772,  735,   64,  772,   65,   63,
       78,   95,  146,  737,  772,   51,  733,   60,  772,  772,
        0,  772,  772,  732,   46,   69,   90,   55,   69,   94,
      702,   48,  701,  694,  115,   41,   45,  708,  122,   79,
       81,   93,  106,  698,  772,  125,  772,  772,  175,  772,
      116,  772,  753,  697,  746,  772,  772,  772,  115,  179,
      772,  772,  772,  772,  772,  772,  192,  739,    0,  772,
      229,  154,    0,  183,  772,    0,  167,  772,  722,  772,
      772,  772,  721,    0,  772,  691,  695,  699,  690,  682,

      681,  685,  693,  157,  696,  695,  166,  178,  675,  681,
      675,  672,  131,  680,  676,  672,  679,  668,    0,  169,
      673,  666,  672,  661,  181,  671,  676,  680,  119,  677,
      183,  664,  186,  195,  668,  664,  178,  193,  660,  205,
      665,  656,  207,  664,  662,  653,  772,  772,  666,  772,
      266,  772,  699,  252,    0,  258,  280,  772,  772,  252,
      295,  272,  302,  772,  772,  650,  659,  665,    0,  650,
      223,  652,  661,  656,  657,  642,  640,  642,  235,  645,
      654,  649,  651,  651,  646,  638,  180,  644,  630,  646,
        0,  641,  631,  635,    0,  636,  641,  636,    0,  617,

      639,  627,  620,  631,  614,  615,  622,  623,  618,  610,
      612,  615,  622,  607,    0,  605,  605,  608,  604,  275,
      616,    0,  615,  605,  609,  604,  597,  611,  613,  612,
      601,  611,  599,  339,  348,  293,  772,  368,  772,  355,
      385,  772,  772,  772,  590,  595,  602,    0,  593,  588,
        0,  594,    0,  595,  303,  584,  590,  581,  590,  579,
      577,  577,  584,  582,    0,    0,  584,  575,  574,  585,
      570,  575,    0,  574,    0,  584,  567,  581,  578,  567,
      580,  564,  578,  573,  568,  558,  556,  557,  554,  567,
      557,  561,  566,  565,  556,    0,  565,  543,    0,  278,

      551,  556,  555,  541,    0,  541,  542,  553,  552,  536,
      392,  404,    0,  283,  539,  550,    0,    0,    0,  573,
      575,    0,    0,  285,  538,  526,  538,  543,  542,  537,
      542,  525,  530,    0,    0,  538,  536,  529,  524,  533,
      521,  517,  516,    0,  515,  530,  529,  512,  525,  516,
        0,  524,  521,  523,  506,  516,  522,  518,    0,  516,
      516,  518,    0,  505,    0,  516,  507,  515,    0,  498,
      509,  494,  505,    0,    0,  510,  509,  505,  484,  486,
      490,  485,    0,    0,  500,  493,    0,    0,    0,    0,
      496,  499,  484,    0,  481,  483,  491,  476,    0,  489,

      476,    0,    0,    0,  492,    0,    0,  472,  490,  483,
        0,  476,  482,  475,  474,  465,    0,  478,    0,    0,
      463,  462,  479,  464,  473,  472,    0,  476,  456,    0,
      471,  454,    0,  455,    0,  466,  453,  454,  297,  463,
      456,    0,  461,  461,    0,  459,    0,  343,    0,    0,
      445,  445,    0,    0,  458,    0,  455,    0,    0,  455,
        0,  441,  439,  455,    0,  441,    0,    0,    0,  391,
        0,  435,    0,  452,    0,    0,  447,  433,  432,  446,
      344,  383,  487,    0,  426,  418,  420,  395,  412,  339,
      394,  397,  390,  772,  389,  407,  389,    0,  394,  403,

      384,  393,  381,  381,  381,    0,  391,  374,    0,  371,
      384,  375,  360,  355,  347,  354,    0,  345,  331,  332,
      316,  295,  298,  292,  323,  299,  321,  298,  289,  286,
      249,  772,  237,  772,  213,  214,  215,    0,  168,  152,
      105,  772,  772,  772,  107,  772,  772,  460,  466,  468,
      474,  480,   95,  486
    } ;

static yyconst flex_int16_t yy_def[555] =
    {   0,
      547,    1,  547,  547,  547,  547,  547,  548,  547,  547,
      547,  547,  549,  547,  547,  547,  547,  547,  547,  547,
      547,  547,  547,  547,  547,  547,  547,  547,  547,  547,
      550,  547,  547,  547,  550,  550,  550,  550,  550,  550,
      550,  550,  550,  550,  550,  550,  550,  550,  550,  550,
      550,  550,  550,  550,  547,  547,  547,  547,  547,  547,
      548,  547,  548,  547,  547,  547,  547,  547,  549,  549,
      547,  547,  547,  547,  547,  547,  547,  551,  552,  547,
      547,   22,   23,  547,  547,  553,  547,  547,  547,  547,
      547,  547,  547,  550,  547,  550,  550,  550,  550,  550,

      550,  550,  550,  550,  550,  550,  550,  550,  550,  550,
      550,  550,  550,  550,  550,  550,  550,  550,  550,  550,
      550,  550,  550,  550,  550,  550,  550,  550,  550,  550,
      550,  550,  550,  550,  550,  550,  550,  550,  550,  550,
      550,  550,  550,  550,  550,  550,  547,  547,  547,  547,
      547,  547,  551,  551,  552,   81,  547,  547,  547,  547,
      547,  553,  547,  547,  547,  550,  550,  550,  550,  550,
      550,  550,  550,  550,  550,  550,  550,  550,  550,  550,
      550,  550,  550,  550,  550,  550,  550,  550,  550,  550,
      550,  550,  550,  550,  550,  550,  550,  550,  550,  550,

      550,  550,  550,  550,  550,  550,  550,  550,  550,  550,
      550,  550,  550,  550,  550,  550,  550,  550,  550,  550,
      550,  550,  550,  550,  550,  550,  550,  550,  550,  550,
      550,  550,  547,  547,  547,  551,  547,  547,  547,  547,
      547,  547,  547,  547,  550,  550,  550,  550,  550,  550,
      550,  550,  550,  550,  550,  550,  550,  550,  550,  550,
      550,  550,  550,  550,  550,  550,  550,  550,  550,  550,
      550,  550,  550,  550,  550,  550,  550,  550,  550,  550,
      550,  550,  550,  550,  550,  550,  550,  550,  550,  550,
      550,  550,  550,  550,  550,  550,  550,  550,  550,  550,

      550,  550,  550,  550,  550,  550,  550,  550,  550,  547,
      547,  547,  550,  550,  550,  550,  550,  550,  550,  550,
      550,  550,  550,  550,  550,  550,  550,  550,  550,  550,
      550,  550,  550,  550,  550,  550,  550,  550,  550,  550,
      550,  550,  550,  550,  550,  550,  550,  550,  550,  550,
      550,  550,  550,  550,  550,  550,  550,  550,  550,  550,
      550,  550,  550,  550,  550,  550,  550,  550,  550,  550,
      547,  550,  550,  550,  550,  550,  550,  550,  550,  550,
      550,  550,  550,  550,  550,  550,  550,  550,  550,  550,
      550,  550,  550,  550,  550,  550,  550,  550,  550,  550,

      550,  550,  550,  550,  550,  550,  550,  550,  550,  550,
      550,  550,  550,  550,  550,  550,  550,  547,  550,  550,
      550,  550,  550,  550,  550,  550,  550,  550,  550,  550,
      550,  550,  550,  550,  550,  550,  550,  550,  550,  550,
      550,  550,  550,  550,  550,  550,  550,  547,  550,  550,
      550,  550,  550,  550,  550,  550,  550,  550,  550,  550,
      550,  550,  550,  550,  550,  550,  550,  550,  550,  547,
      554,  550,  550,  550,  550,  550,  550,  550,  550,  550,
      547,  547,  554,  550,  550,  550,  550,  550,  550,  547,
      547,  547,  547,  547,  550,  550,  550,  550,  550,  547,

      547,  547,  547,  547,  547,  550,  550,  550,  550,  547,
      547,  547,  547,  547,  547,  550,  550,  547,  547,  547,
      547,  547,  547,  550,  547,  547,  547,  547,  547,  547,
      550,  547,  547,  547,  547,  547,  547,  550,  547,  547,
      547,  547,  547,  547,  547,  547,    0,  547,  547,  547,
      547,  547,  547,  547
    } ;

static yyconst flex_uint16_t yy_nxt[847] =
    {   0,
        4,    5,    6,    5,    7,    8,    9,   10,   11,   12,
       13,   14,   15,   16,   17,   18,   19,   20,   21,   22,
       23,   23,   23,   23,   23,   23,   24,   25,   26,   27,
       28,   29,   30,   31,   31,   31,   31,   31,   31,   31,
       32,    4,   33,   34,   31,   35,   36,   37,   38,   39,
       40,   41,   31,   42,   31,   43,   44,   45,   46,   47,
       31,   48,   49,   50,   51,   52,   53,   54,   31,   31,
       55,   56,   57,   58,   59,   62,   59,   67,   72,   89,
       90,   74,   77,   77,   77,   77,   77,   77,   77,   92,
       93,   78,   96,   73,   75,   76,   79,   68,  119,  162,

      127,   97,  128,   98,  108,  120,  129,   80,   99,  130,
      100,   63,   81,  109,   82,   82,   82,   82,   82,   82,
       83,   62,  101,  110,  111,  150,  112,  102,  136,   84,
      103,  137,   85,   85,   86,  104,  113,  546,  140,  114,
      138,   87,  105,  141,   84,  106,  142,  139,  107,  115,
       85,  143,  116,  144,  147,  117,   70,   63,  145,   85,
      123,  545,   86,   81,  124,   83,   83,   83,   83,   83,
       83,   83,  205,  125,  132,  133,   59,  206,   59,  126,
       84,  547,  544,   85,   85,  134,  163,  163,  135,   69,
      187,  159,  159,  547,  188,   84,  148,  160,  543,  160,

      547,   85,  161,  161,  161,  161,  161,  161,  161,  159,
       85,   77,   77,   77,   77,   77,   77,   77,  159,  174,
      175,  547,  178,  179,  194,  180,  151,  152,  181,  152,
      200,  219,  195,  182,  208,  267,  209,  212,  268,  220,
      214,  151,  152,  215,  201,  542,  210,  152,  156,  156,
      156,  156,  156,  156,  156,  213,  216,  221,  224,  541,
      228,  222,  229,  157,  158,  236,  158,  225,  249,  540,
      237,  161,  161,  161,  161,  161,  161,  161,  157,  158,
      234,  250,  234,  539,  158,  235,  235,  235,  235,  235,
      235,  235,  238,  239,  240,  239,  240,  258,  259,  241,

      241,  241,  241,  241,  241,  241,  236,  238,  239,  243,
      243,  547,  538,  239,  161,  161,  161,  161,  161,  161,
      161,  163,  163,  320,  297,  321,  360,  243,  372,  378,
      242,  361,  242,  298,  379,  362,  243,  537,  536,  244,
      244,  373,  463,  535,  464,  242,  470,  481,  471,  471,
      242,  534,  533,  532,  531,  530,  529,  244,  235,  235,
      235,  235,  235,  235,  235,  528,  244,  235,  235,  235,
      235,  235,  235,  235,  241,  241,  241,  241,  241,  241,
      241,  527,  311,  152,  311,  152,  526,  312,  312,  312,
      312,  312,  312,  312,  481,  500,  471,  525,  152,  524,

      523,  501,  502,  152,  241,  241,  241,  241,  241,  241,
      241,  312,  312,  312,  312,  312,  312,  312,  522,  482,
      158,  521,  158,  312,  312,  312,  312,  312,  312,  312,
      490,  520,  519,  491,  518,  158,  492,  517,  516,  239,
      158,  239,  515,  514,  513,  493,  512,  511,  510,  509,
      508,  507,  506,  505,  239,  504,  503,  499,  498,  239,
       61,   61,   61,   61,   61,   61,   69,   69,   69,  497,
       69,   69,   94,   94,  153,  153,  153,  153,  153,  153,
      155,  496,  155,  155,  155,  155,  483,  483,  495,  483,
      483,  483,  494,  489,  488,  487,  486,  485,  484,  480,

      479,  478,  477,  476,  475,  474,  473,  472,  469,  468,
      467,  466,  465,  462,  461,  460,  459,  458,  457,  456,
      455,  454,  453,  452,  451,  450,  449,  448,  447,  446,
      445,  444,  443,  442,  441,  440,  439,  438,  437,  436,
      435,  434,  433,  432,  431,  430,  429,  428,  427,  426,
      425,  424,  423,  422,  421,  420,  419,  418,  417,  416,
      415,  414,  413,  412,  411,  410,  409,  408,  407,  406,
      405,  404,  403,  402,  401,  400,  399,  398,  397,  396,
      395,  394,  393,  392,  391,  390,  389,  388,  387,  386,
      385,  384,  383,  382,  381,  380,  377,  376,  375,  374,

      371,  370,  369,  368,  367,  366,  365,  364,  363,  359,
      358,  357,  356,  355,  354,  353,  352,  351,  350,  349,
      348,  347,  346,  345,  344,  343,  342,  341,  340,  339,
      338,  337,  336,  335,  334,  333,  332,  331,  330,  329,
      328,  327,  326,  325,  324,  323,  322,  319,  318,  317,
      316,  315,  314,  313,  310,  309,  308,  307,  306,  305,
      304,  303,  302,  301,  300,  299,  296,  295,  294,  293,
      292,  291,  290,  289,  288,  287,  286,  285,  284,  283,
      282,  281,  280,  279,  278,  277,  276,  275,  274,  273,
      272,  271,  270,  269,  266,  265,  264,  263,  262,  261,

      260,  257,  256,  255,  254,  253,  252,  251,  248,  247,
      246,  245,  154,  233,  232,  231,  230,  227,  226,  223,
      218,  217,  211,  207,  204,  203,  202,  199,  198,  197,
      196,  193,  192,  191,  190,  189,  186,  185,  184,  183,
      177,  176,  173,  172,  171,  170,  169,  168,  167,  166,
      165,  164,  154,   65,  149,  547,  146,  131,  122,  121,
      118,   95,   91,   88,   71,   70,   66,   65,   64,   60,
      547,    3,  547,  547,  547,  547,  547,  547,  547,  547,
      547,  547,  547,  547,  547,  547,  547,  547,  547,  547,
      547,  547,  547,  547,  547,  547,  547,  547,  547,  547,

      547,  547,  547,  547,  547,  547,  547,  547,  547,  547,
      547,  547,  547,  547,  547,  547,  547,  547,  547,  547,
      547,  547,  547,  547,  547,  547,  547,  547,  547,  547,
      547,  547,  547,  547,  547,  547,  547,  547,  547,  547,
      547,  547,  547,  547,  547,  547
    } ;

static yyconst flex_int16_t yy_chk[847] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    5,    8,    5,   12,   17,   26,
       26,   19,   20,   20,   20,   20,   20,   20,   20,   28,
       28,   21,   35,   17,   19,   19,   21,   12,   42,  553,

       46,   35,   46,   35,   38,   42,   47,   21,   35,   47,
       35,    8,   22,   38,   22,   22,   22,   22,   22,   22,
       22,   61,   36,   38,   39,   69,   39,   36,   50,   22,
       36,   50,   22,   22,   22,   37,   39,  545,   51,   40,
       50,   22,   37,   51,   22,   37,   52,   50,   37,   40,
       22,   52,   40,   53,   56,   40,   69,   61,   53,   22,
       45,  541,   22,   23,   45,   23,   23,   23,   23,   23,
       23,   23,  129,   45,   49,   49,   59,  129,   59,   45,
       23,   70,  540,   23,   23,   49,   87,   87,   49,   70,
      113,   82,   82,   82,  113,   23,   56,   84,  539,   84,

       82,   23,   84,   84,   84,   84,   84,   84,   84,   82,
       23,   77,   77,   77,   77,   77,   77,   77,   82,  104,
      104,   82,  107,  107,  120,  108,   77,   77,  108,   77,
      125,  137,  120,  108,  131,  187,  131,  133,  187,  137,
      134,   77,   77,  134,  125,  537,  131,   77,   81,   81,
       81,   81,   81,   81,   81,  133,  134,  138,  140,  536,
      143,  138,  143,   81,   81,  154,   81,  140,  171,  535,
      154,  160,  160,  160,  160,  160,  160,  160,   81,   81,
      151,  171,  151,  533,   81,  151,  151,  151,  151,  151,
      151,  151,  156,  156,  157,  156,  157,  179,  179,  157,

      157,  157,  157,  157,  157,  157,  236,  156,  156,  162,
      162,  236,  531,  156,  161,  161,  161,  161,  161,  161,
      161,  163,  163,  255,  220,  255,  300,  162,  314,  324,
      161,  300,  161,  220,  324,  300,  162,  530,  529,  163,
      163,  314,  439,  528,  439,  161,  448,  481,  448,  481,
      161,  527,  526,  525,  524,  523,  522,  163,  234,  234,
      234,  234,  234,  234,  234,  521,  163,  235,  235,  235,
      235,  235,  235,  235,  240,  240,  240,  240,  240,  240,
      240,  520,  238,  235,  238,  235,  519,  238,  238,  238,
      238,  238,  238,  238,  470,  490,  470,  518,  235,  516,

      515,  490,  490,  235,  241,  241,  241,  241,  241,  241,
      241,  311,  311,  311,  311,  311,  311,  311,  514,  470,
      241,  513,  241,  312,  312,  312,  312,  312,  312,  312,
      482,  512,  511,  482,  510,  241,  482,  508,  507,  312,
      241,  312,  505,  504,  503,  482,  502,  501,  500,  499,
      497,  496,  495,  493,  312,  492,  491,  489,  488,  312,
      548,  548,  548,  548,  548,  548,  549,  549,  549,  487,
      549,  549,  550,  550,  551,  551,  551,  551,  551,  551,
      552,  486,  552,  552,  552,  552,  554,  554,  485,  554,
      554,  554,  483,  480,  479,  478,  477,  474,  472,  466,

      464,  463,  462,  460,  457,  455,  452,  451,  446,  444,
      443,  441,  440,  438,  437,  436,  434,  432,  431,  429,
      428,  426,  425,  424,  423,  422,  421,  418,  416,  415,
      414,  413,  412,  410,  409,  408,  405,  401,  400,  398,
      397,  396,  395,  393,  392,  391,  386,  385,  382,  381,
      380,  379,  378,  377,  376,  373,  372,  371,  370,  368,
      367,  366,  364,  362,  361,  360,  358,  357,  356,  355,
      354,  353,  352,  350,  349,  348,  347,  346,  345,  343,
      342,  341,  340,  339,  338,  337,  336,  333,  332,  331,
      330,  329,  328,  327,  326,  325,  321,  320,  316,  315,

      310,  309,  308,  307,  306,  304,  303,  302,  301,  298,
      297,  295,  294,  293,  292,  291,  290,  289,  288,  287,
      286,  285,  284,  283,  282,  281,  280,  279,  278,  277,
      276,  274,  272,  271,  270,  269,  268,  267,  264,  263,
      262,  261,  260,  259,  258,  257,  256,  254,  252,  250,
      249,  247,  246,  245,  233,  232,  231,  230,  229,  228,
      227,  226,  225,  224,  223,  221,  219,  218,  217,  216,
      214,  213,  212,  211,  210,  209,  208,  207,  206,  205,
      204,  203,  202,  201,  200,  198,  197,  196,  194,  193,
      192,  190,  189,  188,  186,  185,  184,  183,  182,  181,

      180,  178,  177,  176,  175,  174,  173,  172,  170,  168,
      167,  166,  153,  149,  146,  145,  144,  142,  141,  139,
      136,  135,  132,  130,  128,  127,  126,  124,  123,  122,
      121,  118,  117,  116,  115,  114,  112,  111,  110,  109,
      106,  105,  103,  102,  101,  100,   99,   98,   97,   96,
       93,   89,   78,   65,   64,   63,   54,   48,   44,   43,
       41,   34,   27,   24,   16,   13,   11,   10,    9,    7,
        3,  547,  547,  547,  547,  547,  547,  547,  547,  547,
      547,  547,  547,  547,  547,  547,  547,  547,  547,  547,
      547,  547,  547,  547,  547,  547,  547,  547,  547,  547,

      547,  547,  547,  547,  547,  547,  547,  547,  547,  547,
      547,  547,  547,  547,  547,  547,  547,  547,  547,  547,
      547,  547,  547,  547,  547,  547,  547,  547,  547,  547,
      547,  547,  547,  547,  547,  547,  547,  547,  547,  547,
      547,  547,  547,  547,  547,  547
    } ;

static yy_state_type yy_last_accepting_state;
static char *yy_last_accepting_cpos;

extern int yy_flex_debug;
int yy_flex_debug = 0;

/* The intent behind this definition is that it'll catch
 * any uses of REJECT which flex missed.
 */
#define REJECT reject_used_but_not_detected
#define yymore() yymore_used_but_not_detected
#define YY_MORE_ADJ 0
#define YY_RESTORE_YY_MORE_OFFSET
char *yytext;
#line 1 "clex.l"
#line 12 "clex.l"
#include <stdio.h>
#include <string.h>
#include <stdlib.h>
#include "120gram.tab.h"
#include "token.h"
#include "tree.h"
#include "nonterm.h"
#include "symtab.h"

#define YY_NO_INPUT
#define MAX_INCLUDE_DEPTH 2

extern char *file_name;
struct token *yytoken = NULL;

void lexerr(char *s);
void generate_token(int token_num);
void handle_user_include();
void string_to_sval(char *text);
void char_to_sval(char *text);
void remove_substring(char *s, char *s_remove);
int check_identifier(char *);
//int typenametable_insert(char *s, int cat);
struct tree *leaf_node(int token_num);
void clear_typename_table();
void clear_sysinclude_flags();

/* Save file information for backtracking */
struct fileinfo
{
   int line_num;
   char *file_name;
};

/* Type table */
struct typenametable_entry {
   char *name;
   int category;
   struct typenametable_entry *next;
} *head;


/* Stack for holding includes */
struct fileinfo *include_stack[MAX_INCLUDE_DEPTH];
int top = -1;
int yybuffer_state_counter = 0;

/* Temp storage for ival/sval/dval */
int ival;
char *sval;
double dval;

/* Systeam Includes */
int included_cmath = 0;
int included_cstdlib = 0;
int included_ctime = 0;
int included_fstream = 0;
int included_iostream = 0;
int included_string = 0;
int included_std = 0;

extern int iostream_flag;
extern int namespace_flag;


/* Other counters */
int line_num = 1;
int errors;

#line 905 "lex.yy.c"

#define INITIAL 0

#ifndef YY_NO_UNISTD_H
/* Special case for "unistd.h", since it is non-ANSI. We include it way
 * down here because we want the user's section 1 to have been scanned first.
 * The user has a chance to override it with an option.
 */
#include <unistd.h>
#endif

#ifndef YY_EXTRA_TYPE
#define YY_EXTRA_TYPE void *
#endif

static int yy_init_globals (void );

/* Accessor methods to globals.
   These are made visible to non-reentrant scanners for convenience. */

int yylex_destroy (void );

int yyget_debug (void );

void yyset_debug (int debug_flag  );

YY_EXTRA_TYPE yyget_extra (void );

void yyset_extra (YY_EXTRA_TYPE user_defined  );

FILE *yyget_in (void );

void yyset_in  (FILE * _in_str  );

FILE *yyget_out (void );

void yyset_out  (FILE * _out_str  );

yy_size_t yyget_leng (void );

char *yyget_text (void );

int yyget_lineno (void );

void yyset_lineno (int _line_number  );

/* Macros after this point can all be overridden by user definitions in
 * section 1.
 */

#ifndef YY_SKIP_YYWRAP
#ifdef __cplusplus
extern "C" int yywrap (void );
#else
extern int yywrap (void );
#endif
#endif

#ifndef YY_NO_UNPUT
    
    static void yyunput (int c,char *buf_ptr  );
    
#endif

#ifndef yytext_ptr
static void yy_flex_strncpy (char *,yyconst char *,int );
#endif

#ifdef YY_NEED_STRLEN
static int yy_flex_strlen (yyconst char * );
#endif

#ifndef YY_NO_INPUT

#ifdef __cplusplus
static int yyinput (void );
#else
static int input (void );
#endif

#endif

/* Amount of stuff to slurp up with each read. */
#ifndef YY_READ_BUF_SIZE
#ifdef __ia64__
/* On IA-64, the buffer size is 16k, not 8k */
#define YY_READ_BUF_SIZE 16384
#else
#define YY_READ_BUF_SIZE 8192
#endif /* __ia64__ */
#endif

/* Copy whatever the last rule matched to the standard output. */
#ifndef ECHO
/* This used to be an fputs(), but since the string might contain NUL's,
 * we now use fwrite().
 */
#define ECHO do { if (fwrite( yytext, yyleng, 1, yyout )) {} } while (0)
#endif

/* Gets input and stuffs it into "buf".  number of characters read, or YY_NULL,
 * is returned in "result".
 */
#ifndef YY_INPUT
#define YY_INPUT(buf,result,max_size) \
	if ( YY_CURRENT_BUFFER_LVALUE->yy_is_interactive ) \
		{ \
		int c = '*'; \
		size_t n; \
		for ( n = 0; n < max_size && \
			     (c = getc( yyin )) != EOF && c != '\n'; ++n ) \
			buf[n] = (char) c; \
		if ( c == '\n' ) \
			buf[n++] = (char) c; \
		if ( c == EOF && ferror( yyin ) ) \
			YY_FATAL_ERROR( "input in flex scanner failed" ); \
		result = n; \
		} \
	else \
		{ \
		errno=0; \
		while ( (result = fread(buf, 1, max_size, yyin))==0 && ferror(yyin)) \
			{ \
			if( errno != EINTR) \
				{ \
				YY_FATAL_ERROR( "input in flex scanner failed" ); \
				break; \
				} \
			errno=0; \
			clearerr(yyin); \
			} \
		}\
\

#endif

/* No semi-colon after return; correct usage is to write "yyterminate();" -
 * we don't want an extra ';' after the "return" because that will cause
 * some compilers to complain about unreachable statements.
 */
#ifndef yyterminate
#define yyterminate() return YY_NULL
#endif

/* Number of entries by which start-condition stack grows. */
#ifndef YY_START_STACK_INCR
#define YY_START_STACK_INCR 25
#endif

/* Report a fatal error. */
#ifndef YY_FATAL_ERROR
#define YY_FATAL_ERROR(msg) yy_fatal_error( msg )
#endif

/* end tables serialization structures and prototypes */

/* Default declaration of generated scanner - a define so the user can
 * easily add parameters.
 */
#ifndef YY_DECL
#define YY_DECL_IS_OURS 1

extern int yylex (void);

#define YY_DECL int yylex (void)
#endif /* !YY_DECL */

/* Code executed at the beginning of each rule, after yytext and yyleng
 * have been set up.
 */
#ifndef YY_USER_ACTION
#define YY_USER_ACTION
#endif

/* Code executed at the end of each rule. */
#ifndef YY_BREAK
#define YY_BREAK /*LINTED*/break;
#endif

#define YY_RULE_SETUP \
	YY_USER_ACTION

/** The main scanner function which does all the work.
 */
YY_DECL
{
	yy_state_type yy_current_state;
	char *yy_cp, *yy_bp;
	int yy_act;
    
	if ( !(yy_init) )
		{
		(yy_init) = 1;

#ifdef YY_USER_INIT
		YY_USER_INIT;
#endif

		if ( ! (yy_start) )
			(yy_start) = 1;	/* first start state */

		if ( ! yyin )
			yyin = stdin;

		if ( ! yyout )
			yyout = stdout;

		if ( ! YY_CURRENT_BUFFER ) {
			yyensure_buffer_stack ();
			YY_CURRENT_BUFFER_LVALUE =
				yy_create_buffer(yyin,YY_BUF_SIZE );
		}

		yy_load_buffer_state( );
		}

	{
#line 83 "clex.l"


#line 1126 "lex.yy.c"

	while ( /*CONSTCOND*/1 )		/* loops until end-of-file is reached */
		{
		yy_cp = (yy_c_buf_p);

		/* Support of yytext. */
		*yy_cp = (yy_hold_char);

		/* yy_bp points to the position in yy_ch_buf of the start of
		 * the current run.
		 */
		yy_bp = yy_cp;

		yy_current_state = (yy_start);
yy_match:
		do
			{
			YY_CHAR yy_c = yy_ec[YY_SC_TO_UI(*yy_cp)] ;
			if ( yy_accept[yy_current_state] )
				{
				(yy_last_accepting_state) = yy_current_state;
				(yy_last_accepting_cpos) = yy_cp;
				}
			while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
				{
				yy_current_state = (int) yy_def[yy_current_state];
				if ( yy_current_state >= 548 )
					yy_c = yy_meta[(unsigned int) yy_c];
				}
			yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
			++yy_cp;
			}
		while ( yy_base[yy_current_state] != 772 );

yy_find_action:
		yy_act = yy_accept[yy_current_state];
		if ( yy_act == 0 )
			{ /* have to back up */
			yy_cp = (yy_last_accepting_cpos);
			yy_current_state = (yy_last_accepting_state);
			yy_act = yy_accept[yy_current_state];
			}

		YY_DO_BEFORE_ACTION;

do_action:	/* This label is used only to access EOF actions. */

		switch ( yy_act )
	{ /* beginning of action switch */
			case 0: /* must back up */
			/* undo the effects of YY_DO_BEFORE_ACTION */
			*yy_cp = (yy_hold_char);
			yy_cp = (yy_last_accepting_cpos);
			yy_current_state = (yy_last_accepting_state);
			goto yy_find_action;

case 1:
/* rule 1 can match eol */
YY_RULE_SETUP
#line 85 "clex.l"
{ line_num++; }
	YY_BREAK
case 2:
YY_RULE_SETUP
#line 86 "clex.l"
{  }
	YY_BREAK
case 3:
/* rule 3 can match eol */
YY_RULE_SETUP
#line 88 "clex.l"
{ /*generate_token(COMMENT); return COMMENT;*/ }
	YY_BREAK
case 4:
YY_RULE_SETUP
#line 90 "clex.l"
{ lexerr(yytext); }
	YY_BREAK
case 5:
YY_RULE_SETUP
#line 91 "clex.l"
{ lexerr(yytext); }
	YY_BREAK
case 6:
YY_RULE_SETUP
#line 92 "clex.l"
{ lexerr(yytext); }
	YY_BREAK
case 7:
YY_RULE_SETUP
#line 93 "clex.l"
{ lexerr(yytext); }
	YY_BREAK
case 8:
YY_RULE_SETUP
#line 94 "clex.l"
{ lexerr(yytext); }
	YY_BREAK
case 9:
YY_RULE_SETUP
#line 95 "clex.l"
{ lexerr(yytext); }
	YY_BREAK
case 10:
YY_RULE_SETUP
#line 96 "clex.l"
{ lexerr(yytext); }
	YY_BREAK
case 11:
YY_RULE_SETUP
#line 97 "clex.l"
{ lexerr(yytext); }
	YY_BREAK
case 12:
YY_RULE_SETUP
#line 98 "clex.l"
{ lexerr(yytext); }
	YY_BREAK
case 13:
YY_RULE_SETUP
#line 99 "clex.l"
{ generate_token(BOOL); yylval.treenode = leaf_node(BOOL); return BOOL; }
	YY_BREAK
case 14:
YY_RULE_SETUP
#line 100 "clex.l"
{ generate_token(BREAK); yylval.treenode = leaf_node(BREAK); return BREAK; }
	YY_BREAK
case 15:
YY_RULE_SETUP
#line 101 "clex.l"
{ generate_token(CASE); yylval.treenode = leaf_node(CASE); return CASE; }
	YY_BREAK
case 16:
YY_RULE_SETUP
#line 102 "clex.l"
{ lexerr(yytext); }
	YY_BREAK
case 17:
YY_RULE_SETUP
#line 103 "clex.l"
{ generate_token(CHAR); yylval.treenode = leaf_node(CHAR); return CHAR; }
	YY_BREAK
case 18:
YY_RULE_SETUP
#line 104 "clex.l"
{ lexerr(yytext); }
	YY_BREAK
case 19:
YY_RULE_SETUP
#line 105 "clex.l"
{ lexerr(yytext); }
	YY_BREAK
case 20:
YY_RULE_SETUP
#line 106 "clex.l"
{ generate_token(CLASS); yylval.treenode = leaf_node(CLASS); return CLASS; }
	YY_BREAK
case 21:
YY_RULE_SETUP
#line 107 "clex.l"
{ lexerr(yytext); }
	YY_BREAK
case 22:
YY_RULE_SETUP
#line 108 "clex.l"
{ generate_token(CONST); yylval.treenode = leaf_node(CONST); return CONST; }
	YY_BREAK
case 23:
YY_RULE_SETUP
#line 109 "clex.l"
{ lexerr(yytext); }
	YY_BREAK
case 24:
YY_RULE_SETUP
#line 110 "clex.l"
{ lexerr(yytext); }
	YY_BREAK
case 25:
YY_RULE_SETUP
#line 111 "clex.l"
{ lexerr(yytext); }
	YY_BREAK
case 26:
YY_RULE_SETUP
#line 112 "clex.l"
{ lexerr(yytext); }
	YY_BREAK
case 27:
YY_RULE_SETUP
#line 113 "clex.l"
{ generate_token(DEFAULT); yylval.treenode = leaf_node(DEFAULT); return DEFAULT; }
	YY_BREAK
case 28:
YY_RULE_SETUP
#line 114 "clex.l"
{ generate_token(DELETE); yylval.treenode = leaf_node(DELETE); return DELETE; }
	YY_BREAK
case 29:
YY_RULE_SETUP
#line 115 "clex.l"
{ generate_token(DO); yylval.treenode = leaf_node(DO); return DO; }
	YY_BREAK
case 30:
YY_RULE_SETUP
#line 116 "clex.l"
{ generate_token(DOUBLE); yylval.treenode = leaf_node(DOUBLE); return DOUBLE; }
	YY_BREAK
case 31:
YY_RULE_SETUP
#line 117 "clex.l"
{ lexerr(yytext); }
	YY_BREAK
case 32:
YY_RULE_SETUP
#line 118 "clex.l"
{ generate_token(ELSE); yylval.treenode = leaf_node(ELSE); return ELSE; }
	YY_BREAK
case 33:
YY_RULE_SETUP
#line 119 "clex.l"
{ lexerr(yytext); }
	YY_BREAK
case 34:
YY_RULE_SETUP
#line 120 "clex.l"
{ lexerr(yytext); }
	YY_BREAK
case 35:
YY_RULE_SETUP
#line 121 "clex.l"
{ lexerr(yytext); }
	YY_BREAK
case 36:
YY_RULE_SETUP
#line 122 "clex.l"
{ lexerr(yytext); }
	YY_BREAK
case 37:
YY_RULE_SETUP
#line 123 "clex.l"
{ generate_token(FALSE); yylval.treenode = leaf_node(FALSE); return FALSE; }
	YY_BREAK
case 38:
YY_RULE_SETUP
#line 124 "clex.l"
{ generate_token(FLOAT); yylval.treenode = leaf_node(FLOAT); return FLOAT; }
	YY_BREAK
case 39:
YY_RULE_SETUP
#line 125 "clex.l"
{ generate_token(FOR); yylval.treenode = leaf_node(FOR); return FOR; }
	YY_BREAK
case 40:
YY_RULE_SETUP
#line 126 "clex.l"
{ lexerr(yytext); }
	YY_BREAK
case 41:
YY_RULE_SETUP
#line 127 "clex.l"
{ lexerr(yytext); }
	YY_BREAK
case 42:
YY_RULE_SETUP
#line 128 "clex.l"
{ generate_token(IF); yylval.treenode = leaf_node(IF); return IF; }
	YY_BREAK
case 43:
YY_RULE_SETUP
#line 129 "clex.l"
{ lexerr(yytext); }
	YY_BREAK
case 44:
YY_RULE_SETUP
#line 130 "clex.l"
{ generate_token(INT); yylval.treenode = leaf_node(INT); return INT; }
	YY_BREAK
case 45:
YY_RULE_SETUP
#line 131 "clex.l"
{ generate_token(LONG); yylval.treenode = leaf_node(LONG); return LONG; }
	YY_BREAK
case 46:
YY_RULE_SETUP
#line 132 "clex.l"
{ lexerr(yytext); }
	YY_BREAK
case 47:
YY_RULE_SETUP
#line 133 "clex.l"
{ generate_token(NAMESPACE); yylval.treenode = leaf_node(NAMESPACE); return NAMESPACE; }
	YY_BREAK
case 48:
YY_RULE_SETUP
#line 134 "clex.l"
{ generate_token(NEW); yylval.treenode = leaf_node(NEW); return NEW; }
	YY_BREAK
case 49:
YY_RULE_SETUP
#line 135 "clex.l"
{ lexerr(yytext); }
	YY_BREAK
case 50:
YY_RULE_SETUP
#line 136 "clex.l"
{ lexerr(yytext); }
	YY_BREAK
case 51:
YY_RULE_SETUP
#line 137 "clex.l"
{ lexerr(yytext); }
	YY_BREAK
case 52:
YY_RULE_SETUP
#line 138 "clex.l"
{ lexerr(yytext); }
	YY_BREAK
case 53:
YY_RULE_SETUP
#line 139 "clex.l"
{ lexerr(yytext); }
	YY_BREAK
case 54:
YY_RULE_SETUP
#line 140 "clex.l"
{ lexerr(yytext); }
	YY_BREAK
case 55:
YY_RULE_SETUP
#line 141 "clex.l"
{ lexerr(yytext); }
	YY_BREAK
case 56:
YY_RULE_SETUP
#line 142 "clex.l"
{ generate_token(PRIVATE); yylval.treenode = leaf_node(PRIVATE); return PRIVATE; }
	YY_BREAK
case 57:
YY_RULE_SETUP
#line 143 "clex.l"
{ lexerr(yytext); }
	YY_BREAK
case 58:
YY_RULE_SETUP
#line 144 "clex.l"
{ generate_token(PUBLIC); yylval.treenode = leaf_node(PUBLIC); return PUBLIC; }
	YY_BREAK
case 59:
YY_RULE_SETUP
#line 145 "clex.l"
{ lexerr(yytext); }
	YY_BREAK
case 60:
YY_RULE_SETUP
#line 146 "clex.l"
{ lexerr(yytext); }
	YY_BREAK
case 61:
YY_RULE_SETUP
#line 147 "clex.l"
{ generate_token(RETURN); yylval.treenode = leaf_node(RETURN); return RETURN; }
	YY_BREAK
case 62:
YY_RULE_SETUP
#line 148 "clex.l"
{ generate_token(SHORT); yylval.treenode = leaf_node(SHORT); return SHORT; }
	YY_BREAK
case 63:
YY_RULE_SETUP
#line 149 "clex.l"
{ lexerr(yytext); }
	YY_BREAK
case 64:
YY_RULE_SETUP
#line 150 "clex.l"
{ lexerr(yytext); }
	YY_BREAK
case 65:
YY_RULE_SETUP
#line 151 "clex.l"
{ lexerr(yytext); }
	YY_BREAK
case 66:
YY_RULE_SETUP
#line 152 "clex.l"
{ lexerr(yytext); }
	YY_BREAK
case 67:
YY_RULE_SETUP
#line 153 "clex.l"
{ lexerr(yytext); }
	YY_BREAK
case 68:
YY_RULE_SETUP
#line 154 "clex.l"
{ lexerr(yytext); }
	YY_BREAK
case 69:
YY_RULE_SETUP
#line 155 "clex.l"
{ generate_token(SWITCH); yylval.treenode = leaf_node(SWITCH); return SWITCH; }
	YY_BREAK
case 70:
YY_RULE_SETUP
#line 156 "clex.l"
{ lexerr(yytext); }
	YY_BREAK
case 71:
YY_RULE_SETUP
#line 157 "clex.l"
{ lexerr(yytext); }
	YY_BREAK
case 72:
YY_RULE_SETUP
#line 158 "clex.l"
{ lexerr(yytext); }
	YY_BREAK
case 73:
YY_RULE_SETUP
#line 159 "clex.l"
{ lexerr(yytext); }
	YY_BREAK
case 74:
YY_RULE_SETUP
#line 160 "clex.l"
{ generate_token(TRUE); yylval.treenode = leaf_node(TRUE); return TRUE; }
	YY_BREAK
case 75:
YY_RULE_SETUP
#line 161 "clex.l"
{ lexerr(yytext); }
	YY_BREAK
case 76:
YY_RULE_SETUP
#line 162 "clex.l"
{ lexerr(yytext); }
	YY_BREAK
case 77:
YY_RULE_SETUP
#line 163 "clex.l"
{ lexerr(yytext); }
	YY_BREAK
case 78:
YY_RULE_SETUP
#line 164 "clex.l"
{ lexerr(yytext); }
	YY_BREAK
case 79:
YY_RULE_SETUP
#line 165 "clex.l"
{ lexerr(yytext); }
	YY_BREAK
case 80:
YY_RULE_SETUP
#line 166 "clex.l"
{ generate_token(UNSIGNED); yylval.treenode = leaf_node(UNSIGNED); return UNSIGNED; }
	YY_BREAK
case 81:
YY_RULE_SETUP
#line 167 "clex.l"
{ generate_token(USING); yylval.treenode = leaf_node(USING); return USING; }
	YY_BREAK
case 82:
YY_RULE_SETUP
#line 168 "clex.l"
{ lexerr(yytext); }
	YY_BREAK
case 83:
YY_RULE_SETUP
#line 169 "clex.l"
{ generate_token(VOID); yylval.treenode = leaf_node(VOID); return VOID; }
	YY_BREAK
case 84:
YY_RULE_SETUP
#line 170 "clex.l"
{ lexerr(yytext); }
	YY_BREAK
case 85:
YY_RULE_SETUP
#line 171 "clex.l"
{ lexerr(yytext); }
	YY_BREAK
case 86:
YY_RULE_SETUP
#line 172 "clex.l"
{ generate_token(WHILE); yylval.treenode = leaf_node(WHILE); return WHILE; }
	YY_BREAK
case 87:
YY_RULE_SETUP
#line 173 "clex.l"
{ lexerr(yytext); }
	YY_BREAK
case 88:
YY_RULE_SETUP
#line 174 "clex.l"
{ lexerr(yytext); }
	YY_BREAK
case 89:
YY_RULE_SETUP
#line 175 "clex.l"
{ included_iostream = 1; iostream_flag = 1; }
	YY_BREAK
case 90:
YY_RULE_SETUP
#line 176 "clex.l"
{ included_string = 1; }
	YY_BREAK
case 91:
YY_RULE_SETUP
#line 177 "clex.l"
{ included_ctime = 1; }
	YY_BREAK
case 92:
YY_RULE_SETUP
#line 178 "clex.l"
{ included_cstdlib = 1; }
	YY_BREAK
case 93:
YY_RULE_SETUP
#line 179 "clex.l"
{ included_cmath = 1; }
	YY_BREAK
case 94:
YY_RULE_SETUP
#line 180 "clex.l"
{ included_fstream = 1; }
	YY_BREAK
case 95:
YY_RULE_SETUP
#line 182 "clex.l"
{ included_std = 1; generate_token(STD); yylval.treenode = leaf_node(STD); namespace_flag = 1;
                if (included_string) typenametable_insert("string", CLASS_NAME);
                if (included_iostream)
                {
                   typenametable_insert("ifstream", CLASS_NAME);
                   typenametable_insert("ofstream", CLASS_NAME);
                   typenametable_insert("fstream", CLASS_NAME);
                   typenametable_insert("cout", IDENTIFIER);
                   typenametable_insert("cin", IDENTIFIER);
                   typenametable_insert("endl", IDENTIFIER);
                }
                return STD;
             }
	YY_BREAK
case 96:
YY_RULE_SETUP
#line 197 "clex.l"
{   int cat;
                            cat = check_identifier(yytext);
                            generate_token(cat);
                            yylval.treenode = leaf_node(cat); 
                            return cat;
                        }
	YY_BREAK
case 97:
YY_RULE_SETUP
#line 204 "clex.l"
{ lexerr("Binary not supported"); }
	YY_BREAK
case 98:
YY_RULE_SETUP
#line 206 "clex.l"
{ lexerr("Hex not supported"); }
	YY_BREAK
case 99:
YY_RULE_SETUP
#line 208 "clex.l"
{ lexerr("Octal not supported"); }
	YY_BREAK
case 100:
YY_RULE_SETUP
#line 210 "clex.l"
{ ival = atoi(yytext); generate_token(INTEGER); yylval.treenode = leaf_node(INTEGER); return INTEGER; }
	YY_BREAK
case 101:
/* rule 101 can match eol */
YY_RULE_SETUP
#line 212 "clex.l"
{ char_to_sval(yytext); generate_token(CHARACTER); yylval.treenode = leaf_node(CHARACTER); return CHARACTER; }
	YY_BREAK
case 102:
YY_RULE_SETUP
#line 214 "clex.l"
{ dval = atof(yytext); generate_token(FLOATING); yylval.treenode = leaf_node(FLOATING); return FLOATING; }
	YY_BREAK
case 103:
YY_RULE_SETUP
#line 215 "clex.l"
{ dval = atof(yytext); generate_token(FLOATING); yylval.treenode = leaf_node(FLOATING); return FLOATING; }
	YY_BREAK
case 104:
YY_RULE_SETUP
#line 216 "clex.l"
{ dval = atof(yytext); generate_token(FLOATING); yylval.treenode = leaf_node(FLOATING); return FLOATING; }
	YY_BREAK
case 105:
/* rule 105 can match eol */
YY_RULE_SETUP
#line 218 "clex.l"
{ string_to_sval(yytext); generate_token(STRING); yylval.treenode = leaf_node(STRING); return STRING; }
	YY_BREAK
case 106:
/* rule 106 can match eol */
YY_RULE_SETUP
#line 220 "clex.l"
{ handle_user_include(); }
	YY_BREAK
case 107:
YY_RULE_SETUP
#line 223 "clex.l"
{ generate_token(DOT); yylval.treenode = leaf_node(DOT); return DOT; }
	YY_BREAK
case 108:
YY_RULE_SETUP
#line 224 "clex.l"
{ generate_token(SREQ); yylval.treenode = leaf_node(SREQ); return SREQ; }
	YY_BREAK
case 109:
YY_RULE_SETUP
#line 225 "clex.l"
{ generate_token(SLEQ); yylval.treenode = leaf_node(SLEQ); return SLEQ; }
	YY_BREAK
case 110:
YY_RULE_SETUP
#line 226 "clex.l"
{ generate_token(ADDEQ); yylval.treenode = leaf_node(ADDEQ); return ADDEQ; }
	YY_BREAK
case 111:
YY_RULE_SETUP
#line 227 "clex.l"
{ generate_token(SUBEQ); yylval.treenode = leaf_node(SUBEQ); return SUBEQ; }
	YY_BREAK
case 112:
YY_RULE_SETUP
#line 228 "clex.l"
{ generate_token(MULEQ); yylval.treenode = leaf_node(MULEQ); return MULEQ; }
	YY_BREAK
case 113:
YY_RULE_SETUP
#line 229 "clex.l"
{ generate_token(DIVEQ); yylval.treenode = leaf_node(DIVEQ); return DIVEQ; }
	YY_BREAK
case 114:
YY_RULE_SETUP
#line 230 "clex.l"
{ generate_token(MODEQ); yylval.treenode = leaf_node(MODEQ); return MODEQ; }
	YY_BREAK
case 115:
YY_RULE_SETUP
#line 231 "clex.l"
{ lexerr(yytext); }
	YY_BREAK
case 116:
YY_RULE_SETUP
#line 232 "clex.l"
{ lexerr(yytext); }
	YY_BREAK
case 117:
YY_RULE_SETUP
#line 233 "clex.l"
{ lexerr(yytext); }
	YY_BREAK
case 118:
YY_RULE_SETUP
#line 234 "clex.l"
{ generate_token(SR); yylval.treenode = leaf_node(SR); return SR; }
	YY_BREAK
case 119:
YY_RULE_SETUP
#line 235 "clex.l"
{ generate_token(SL); yylval.treenode = leaf_node(SL); return SL; }
	YY_BREAK
case 120:
YY_RULE_SETUP
#line 236 "clex.l"
{ generate_token(PLUSPLUS); yylval.treenode = leaf_node(PLUSPLUS); return PLUSPLUS; }
	YY_BREAK
case 121:
YY_RULE_SETUP
#line 237 "clex.l"
{ generate_token(MINUSMINUS); yylval.treenode = leaf_node(MINUSMINUS); return MINUSMINUS; }
	YY_BREAK
case 122:
YY_RULE_SETUP
#line 238 "clex.l"
{ generate_token(ARROW); yylval.treenode = leaf_node(ARROW); return ARROW; }
	YY_BREAK
case 123:
YY_RULE_SETUP
#line 239 "clex.l"
{ generate_token(ANDAND); yylval.treenode = leaf_node(ANDAND); return ANDAND; }
	YY_BREAK
case 124:
YY_RULE_SETUP
#line 240 "clex.l"
{ generate_token(OROR); yylval.treenode = leaf_node(OROR); return OROR; }
	YY_BREAK
case 125:
YY_RULE_SETUP
#line 241 "clex.l"
{ generate_token(LTEQ); yylval.treenode = leaf_node(LTEQ); return LTEQ; }
	YY_BREAK
case 126:
YY_RULE_SETUP
#line 242 "clex.l"
{ generate_token(GTEQ); yylval.treenode = leaf_node(GTEQ); return GTEQ; }
	YY_BREAK
case 127:
YY_RULE_SETUP
#line 243 "clex.l"
{ generate_token(EQ); yylval.treenode = leaf_node(EQ); return EQ; }
	YY_BREAK
case 128:
YY_RULE_SETUP
#line 244 "clex.l"
{ generate_token(NOTEQ); yylval.treenode = leaf_node(NOTEQ); return NOTEQ; }
	YY_BREAK
case 129:
YY_RULE_SETUP
#line 245 "clex.l"
{ generate_token(COLONCOLON); yylval.treenode = leaf_node(COLONCOLON); return COLONCOLON; }
	YY_BREAK
case 130:
YY_RULE_SETUP
#line 246 "clex.l"
{ generate_token(SM); yylval.treenode = leaf_node(SM); return SM; }
	YY_BREAK
case 131:
YY_RULE_SETUP
#line 247 "clex.l"
{ generate_token(LC); yylval.treenode = leaf_node(LC); return LC; }
	YY_BREAK
case 132:
YY_RULE_SETUP
#line 248 "clex.l"
{ generate_token(RC); yylval.treenode = leaf_node(RC); return RC; }
	YY_BREAK
case 133:
YY_RULE_SETUP
#line 249 "clex.l"
{ generate_token(CM); yylval.treenode = leaf_node(CM); return CM; }
	YY_BREAK
case 134:
YY_RULE_SETUP
#line 250 "clex.l"
{ generate_token(COLON); yylval.treenode = leaf_node(COLON); return COLON; }
	YY_BREAK
case 135:
YY_RULE_SETUP
#line 251 "clex.l"
{ generate_token(ASN); yylval.treenode = leaf_node(ASN); return ASN; }
	YY_BREAK
case 136:
YY_RULE_SETUP
#line 252 "clex.l"
{ generate_token(LP); yylval.treenode = leaf_node(LP); return LP; }
	YY_BREAK
case 137:
YY_RULE_SETUP
#line 253 "clex.l"
{ generate_token(RP); yylval.treenode = leaf_node(RP); return RP; }
	YY_BREAK
case 138:
YY_RULE_SETUP
#line 254 "clex.l"
{ generate_token(LB); yylval.treenode = leaf_node(LB); return LB; }
	YY_BREAK
case 139:
YY_RULE_SETUP
#line 255 "clex.l"
{ generate_token(RB); yylval.treenode = leaf_node(RB); return RB; }
	YY_BREAK
case 140:
YY_RULE_SETUP
#line 256 "clex.l"
{ generate_token(AND); yylval.treenode = leaf_node(AND); return AND; }
	YY_BREAK
case 141:
YY_RULE_SETUP
#line 257 "clex.l"
{ generate_token(BANG); yylval.treenode = leaf_node(BANG); return BANG; }
	YY_BREAK
case 142:
YY_RULE_SETUP
#line 258 "clex.l"
{ generate_token(NOT); yylval.treenode = leaf_node(NOT); return NOT; }
	YY_BREAK
case 143:
YY_RULE_SETUP
#line 259 "clex.l"
{ generate_token(MINUS); yylval.treenode = leaf_node(MINUS); return MINUS; }
	YY_BREAK
case 144:
YY_RULE_SETUP
#line 260 "clex.l"
{ generate_token(PLUS); yylval.treenode = leaf_node(PLUS); return PLUS; }
	YY_BREAK
case 145:
YY_RULE_SETUP
#line 261 "clex.l"
{ generate_token(MUL); yylval.treenode = leaf_node(MUL); return MUL; }
	YY_BREAK
case 146:
YY_RULE_SETUP
#line 262 "clex.l"
{ generate_token(DIV); yylval.treenode = leaf_node(DIV); return DIV; }
	YY_BREAK
case 147:
YY_RULE_SETUP
#line 263 "clex.l"
{ generate_token(MOD); yylval.treenode = leaf_node(MOD); return MOD; }
	YY_BREAK
case 148:
YY_RULE_SETUP
#line 264 "clex.l"
{ generate_token(LT); yylval.treenode = leaf_node(LT); return LT; }
	YY_BREAK
case 149:
YY_RULE_SETUP
#line 265 "clex.l"
{ generate_token(GT); yylval.treenode = leaf_node(GT); return GT; }
	YY_BREAK
case 150:
YY_RULE_SETUP
#line 266 "clex.l"
{ generate_token(ER); yylval.treenode = leaf_node(ER); return ER; }
	YY_BREAK
case 151:
YY_RULE_SETUP
#line 267 "clex.l"
{ generate_token(OR); yylval.treenode = leaf_node(OR); return OR; }
	YY_BREAK
case 152:
YY_RULE_SETUP
#line 268 "clex.l"
{ generate_token(QUEST); yylval.treenode = leaf_node(QUEST); return QUEST; }
	YY_BREAK
case 153:
YY_RULE_SETUP
#line 269 "clex.l"
{ lexerr(yytext); }
	YY_BREAK
case 154:
YY_RULE_SETUP
#line 270 "clex.l"
{ lexerr(yytext); }
	YY_BREAK
case 155:
YY_RULE_SETUP
#line 272 "clex.l"
ECHO;
	YY_BREAK
#line 1980 "lex.yy.c"
case YY_STATE_EOF(INITIAL):
	yyterminate();

	case YY_END_OF_BUFFER:
		{
		/* Amount of text matched not including the EOB char. */
		int yy_amount_of_matched_text = (int) (yy_cp - (yytext_ptr)) - 1;

		/* Undo the effects of YY_DO_BEFORE_ACTION. */
		*yy_cp = (yy_hold_char);
		YY_RESTORE_YY_MORE_OFFSET

		if ( YY_CURRENT_BUFFER_LVALUE->yy_buffer_status == YY_BUFFER_NEW )
			{
			/* We're scanning a new file or input source.  It's
			 * possible that this happened because the user
			 * just pointed yyin at a new source and called
			 * yylex().  If so, then we have to assure
			 * consistency between YY_CURRENT_BUFFER and our
			 * globals.  Here is the right place to do so, because
			 * this is the first action (other than possibly a
			 * back-up) that will match for the new input source.
			 */
			(yy_n_chars) = YY_CURRENT_BUFFER_LVALUE->yy_n_chars;
			YY_CURRENT_BUFFER_LVALUE->yy_input_file = yyin;
			YY_CURRENT_BUFFER_LVALUE->yy_buffer_status = YY_BUFFER_NORMAL;
			}

		/* Note that here we test for yy_c_buf_p "<=" to the position
		 * of the first EOB in the buffer, since yy_c_buf_p will
		 * already have been incremented past the NUL character
		 * (since all states make transitions on EOB to the
		 * end-of-buffer state).  Contrast this with the test
		 * in input().
		 */
		if ( (yy_c_buf_p) <= &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] )
			{ /* This was really a NUL. */
			yy_state_type yy_next_state;

			(yy_c_buf_p) = (yytext_ptr) + yy_amount_of_matched_text;

			yy_current_state = yy_get_previous_state(  );

			/* Okay, we're now positioned to make the NUL
			 * transition.  We couldn't have
			 * yy_get_previous_state() go ahead and do it
			 * for us because it doesn't know how to deal
			 * with the possibility of jamming (and we don't
			 * want to build jamming into it because then it
			 * will run more slowly).
			 */

			yy_next_state = yy_try_NUL_trans( yy_current_state );

			yy_bp = (yytext_ptr) + YY_MORE_ADJ;

			if ( yy_next_state )
				{
				/* Consume the NUL. */
				yy_cp = ++(yy_c_buf_p);
				yy_current_state = yy_next_state;
				goto yy_match;
				}

			else
				{
				yy_cp = (yy_c_buf_p);
				goto yy_find_action;
				}
			}

		else switch ( yy_get_next_buffer(  ) )
			{
			case EOB_ACT_END_OF_FILE:
				{
				(yy_did_buffer_switch_on_eof) = 0;

				if ( yywrap( ) )
					{
					/* Note: because we've taken care in
					 * yy_get_next_buffer() to have set up
					 * yytext, we can now set up
					 * yy_c_buf_p so that if some total
					 * hoser (like flex itself) wants to
					 * call the scanner after we return the
					 * YY_NULL, it'll still work - another
					 * YY_NULL will get returned.
					 */
					(yy_c_buf_p) = (yytext_ptr) + YY_MORE_ADJ;

					yy_act = YY_STATE_EOF(YY_START);
					goto do_action;
					}

				else
					{
					if ( ! (yy_did_buffer_switch_on_eof) )
						YY_NEW_FILE;
					}
				break;
				}

			case EOB_ACT_CONTINUE_SCAN:
				(yy_c_buf_p) =
					(yytext_ptr) + yy_amount_of_matched_text;

				yy_current_state = yy_get_previous_state(  );

				yy_cp = (yy_c_buf_p);
				yy_bp = (yytext_ptr) + YY_MORE_ADJ;
				goto yy_match;

			case EOB_ACT_LAST_MATCH:
				(yy_c_buf_p) =
				&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)];

				yy_current_state = yy_get_previous_state(  );

				yy_cp = (yy_c_buf_p);
				yy_bp = (yytext_ptr) + YY_MORE_ADJ;
				goto yy_find_action;
			}
		break;
		}

	default:
		YY_FATAL_ERROR(
			"fatal flex scanner internal error--no action found" );
	} /* end of action switch */
		} /* end of scanning one token */
	} /* end of user's declarations */
} /* end of yylex */

/* yy_get_next_buffer - try to read in a new buffer
 *
 * Returns a code representing an action:
 *	EOB_ACT_LAST_MATCH -
 *	EOB_ACT_CONTINUE_SCAN - continue scanning from current position
 *	EOB_ACT_END_OF_FILE - end of file
 */
static int yy_get_next_buffer (void)
{
    	char *dest = YY_CURRENT_BUFFER_LVALUE->yy_ch_buf;
	char *source = (yytext_ptr);
	yy_size_t number_to_move, i;
	int ret_val;

	if ( (yy_c_buf_p) > &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars) + 1] )
		YY_FATAL_ERROR(
		"fatal flex scanner internal error--end of buffer missed" );

	if ( YY_CURRENT_BUFFER_LVALUE->yy_fill_buffer == 0 )
		{ /* Don't try to fill the buffer, so this is an EOF. */
		if ( (yy_c_buf_p) - (yytext_ptr) - YY_MORE_ADJ == 1 )
			{
			/* We matched a single character, the EOB, so
			 * treat this as a final EOF.
			 */
			return EOB_ACT_END_OF_FILE;
			}

		else
			{
			/* We matched some text prior to the EOB, first
			 * process it.
			 */
			return EOB_ACT_LAST_MATCH;
			}
		}

	/* Try to read more data. */

	/* First move last chars to start of buffer. */
	number_to_move = (yy_size_t) ((yy_c_buf_p) - (yytext_ptr)) - 1;

	for ( i = 0; i < number_to_move; ++i )
		*(dest++) = *(source++);

	if ( YY_CURRENT_BUFFER_LVALUE->yy_buffer_status == YY_BUFFER_EOF_PENDING )
		/* don't do the read, it's not guaranteed to return an EOF,
		 * just force an EOF
		 */
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars) = 0;

	else
		{
			yy_size_t num_to_read =
			YY_CURRENT_BUFFER_LVALUE->yy_buf_size - number_to_move - 1;

		while ( num_to_read <= 0 )
			{ /* Not enough room in the buffer - grow it. */

			/* just a shorter name for the current buffer */
			YY_BUFFER_STATE b = YY_CURRENT_BUFFER_LVALUE;

			int yy_c_buf_p_offset =
				(int) ((yy_c_buf_p) - b->yy_ch_buf);

			if ( b->yy_is_our_buffer )
				{
				yy_size_t new_size = b->yy_buf_size * 2;

				if ( new_size <= 0 )
					b->yy_buf_size += b->yy_buf_size / 8;
				else
					b->yy_buf_size *= 2;

				b->yy_ch_buf = (char *)
					/* Include room in for 2 EOB chars. */
					yyrealloc((void *) b->yy_ch_buf,b->yy_buf_size + 2  );
				}
			else
				/* Can't grow it, we don't own it. */
				b->yy_ch_buf = 0;

			if ( ! b->yy_ch_buf )
				YY_FATAL_ERROR(
				"fatal error - scanner input buffer overflow" );

			(yy_c_buf_p) = &b->yy_ch_buf[yy_c_buf_p_offset];

			num_to_read = YY_CURRENT_BUFFER_LVALUE->yy_buf_size -
						number_to_move - 1;

			}

		if ( num_to_read > YY_READ_BUF_SIZE )
			num_to_read = YY_READ_BUF_SIZE;

		/* Read in more data. */
		YY_INPUT( (&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[number_to_move]),
			(yy_n_chars), num_to_read );

		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	if ( (yy_n_chars) == 0 )
		{
		if ( number_to_move == YY_MORE_ADJ )
			{
			ret_val = EOB_ACT_END_OF_FILE;
			yyrestart(yyin  );
			}

		else
			{
			ret_val = EOB_ACT_LAST_MATCH;
			YY_CURRENT_BUFFER_LVALUE->yy_buffer_status =
				YY_BUFFER_EOF_PENDING;
			}
		}

	else
		ret_val = EOB_ACT_CONTINUE_SCAN;

	if ((int) ((yy_n_chars) + number_to_move) > YY_CURRENT_BUFFER_LVALUE->yy_buf_size) {
		/* Extend the array by 50%, plus the number we really need. */
		int new_size = (yy_n_chars) + number_to_move + ((yy_n_chars) >> 1);
		YY_CURRENT_BUFFER_LVALUE->yy_ch_buf = (char *) yyrealloc((void *) YY_CURRENT_BUFFER_LVALUE->yy_ch_buf,new_size  );
		if ( ! YY_CURRENT_BUFFER_LVALUE->yy_ch_buf )
			YY_FATAL_ERROR( "out of dynamic memory in yy_get_next_buffer()" );
	}

	(yy_n_chars) += number_to_move;
	YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] = YY_END_OF_BUFFER_CHAR;
	YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars) + 1] = YY_END_OF_BUFFER_CHAR;

	(yytext_ptr) = &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[0];

	return ret_val;
}

/* yy_get_previous_state - get the state just before the EOB char was reached */

    static yy_state_type yy_get_previous_state (void)
{
	yy_state_type yy_current_state;
	char *yy_cp;
    
	yy_current_state = (yy_start);

	for ( yy_cp = (yytext_ptr) + YY_MORE_ADJ; yy_cp < (yy_c_buf_p); ++yy_cp )
		{
		YY_CHAR yy_c = (*yy_cp ? yy_ec[YY_SC_TO_UI(*yy_cp)] : 1);
		if ( yy_accept[yy_current_state] )
			{
			(yy_last_accepting_state) = yy_current_state;
			(yy_last_accepting_cpos) = yy_cp;
			}
		while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
			{
			yy_current_state = (int) yy_def[yy_current_state];
			if ( yy_current_state >= 548 )
				yy_c = yy_meta[(unsigned int) yy_c];
			}
		yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
		}

	return yy_current_state;
}

/* yy_try_NUL_trans - try to make a transition on the NUL character
 *
 * synopsis
 *	next_state = yy_try_NUL_trans( current_state );
 */
    static yy_state_type yy_try_NUL_trans  (yy_state_type yy_current_state )
{
	int yy_is_jam;
    	char *yy_cp = (yy_c_buf_p);

	YY_CHAR yy_c = 1;
	if ( yy_accept[yy_current_state] )
		{
		(yy_last_accepting_state) = yy_current_state;
		(yy_last_accepting_cpos) = yy_cp;
		}
	while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
		{
		yy_current_state = (int) yy_def[yy_current_state];
		if ( yy_current_state >= 548 )
			yy_c = yy_meta[(unsigned int) yy_c];
		}
	yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
	yy_is_jam = (yy_current_state == 547);

		return yy_is_jam ? 0 : yy_current_state;
}

#ifndef YY_NO_UNPUT

    static void yyunput (int c, char * yy_bp )
{
	char *yy_cp;
    
    yy_cp = (yy_c_buf_p);

	/* undo effects of setting up yytext */
	*yy_cp = (yy_hold_char);

	if ( yy_cp < YY_CURRENT_BUFFER_LVALUE->yy_ch_buf + 2 )
		{ /* need to shift things up to make room */
		/* +2 for EOB chars. */
		yy_size_t number_to_move = (yy_n_chars) + 2;
		char *dest = &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[
					YY_CURRENT_BUFFER_LVALUE->yy_buf_size + 2];
		char *source =
				&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[number_to_move];

		while ( source > YY_CURRENT_BUFFER_LVALUE->yy_ch_buf )
			*--dest = *--source;

		yy_cp += (int) (dest - source);
		yy_bp += (int) (dest - source);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars =
			(yy_n_chars) = YY_CURRENT_BUFFER_LVALUE->yy_buf_size;

		if ( yy_cp < YY_CURRENT_BUFFER_LVALUE->yy_ch_buf + 2 )
			YY_FATAL_ERROR( "flex scanner push-back overflow" );
		}

	*--yy_cp = (char) c;

	(yytext_ptr) = yy_bp;
	(yy_hold_char) = *yy_cp;
	(yy_c_buf_p) = yy_cp;
}

#endif

#ifndef YY_NO_INPUT
#ifdef __cplusplus
    static int yyinput (void)
#else
    static int input  (void)
#endif

{
	int c;
    
	*(yy_c_buf_p) = (yy_hold_char);

	if ( *(yy_c_buf_p) == YY_END_OF_BUFFER_CHAR )
		{
		/* yy_c_buf_p now points to the character we want to return.
		 * If this occurs *before* the EOB characters, then it's a
		 * valid NUL; if not, then we've hit the end of the buffer.
		 */
		if ( (yy_c_buf_p) < &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] )
			/* This was really a NUL. */
			*(yy_c_buf_p) = '\0';

		else
			{ /* need more input */
			yy_size_t offset = (yy_c_buf_p) - (yytext_ptr);
			++(yy_c_buf_p);

			switch ( yy_get_next_buffer(  ) )
				{
				case EOB_ACT_LAST_MATCH:
					/* This happens because yy_g_n_b()
					 * sees that we've accumulated a
					 * token and flags that we need to
					 * try matching the token before
					 * proceeding.  But for input(),
					 * there's no matching to consider.
					 * So convert the EOB_ACT_LAST_MATCH
					 * to EOB_ACT_END_OF_FILE.
					 */

					/* Reset buffer status. */
					yyrestart(yyin );

					/*FALLTHROUGH*/

				case EOB_ACT_END_OF_FILE:
					{
					if ( yywrap( ) )
						return EOF;

					if ( ! (yy_did_buffer_switch_on_eof) )
						YY_NEW_FILE;
#ifdef __cplusplus
					return yyinput();
#else
					return input();
#endif
					}

				case EOB_ACT_CONTINUE_SCAN:
					(yy_c_buf_p) = (yytext_ptr) + offset;
					break;
				}
			}
		}

	c = *(unsigned char *) (yy_c_buf_p);	/* cast for 8-bit char's */
	*(yy_c_buf_p) = '\0';	/* preserve yytext */
	(yy_hold_char) = *++(yy_c_buf_p);

	return c;
}
#endif	/* ifndef YY_NO_INPUT */

/** Immediately switch to a different input stream.
 * @param input_file A readable stream.
 * 
 * @note This function does not reset the start condition to @c INITIAL .
 */
    void yyrestart  (FILE * input_file )
{
    
	if ( ! YY_CURRENT_BUFFER ){
        yyensure_buffer_stack ();
		YY_CURRENT_BUFFER_LVALUE =
            yy_create_buffer(yyin,YY_BUF_SIZE );
	}

	yy_init_buffer(YY_CURRENT_BUFFER,input_file );
	yy_load_buffer_state( );
}

/** Switch to a different input buffer.
 * @param new_buffer The new input buffer.
 * 
 */
    void yy_switch_to_buffer  (YY_BUFFER_STATE  new_buffer )
{
    
	/* TODO. We should be able to replace this entire function body
	 * with
	 *		yypop_buffer_state();
	 *		yypush_buffer_state(new_buffer);
     */
	yyensure_buffer_stack ();
	if ( YY_CURRENT_BUFFER == new_buffer )
		return;

	if ( YY_CURRENT_BUFFER )
		{
		/* Flush out information for old buffer. */
		*(yy_c_buf_p) = (yy_hold_char);
		YY_CURRENT_BUFFER_LVALUE->yy_buf_pos = (yy_c_buf_p);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	YY_CURRENT_BUFFER_LVALUE = new_buffer;
	yy_load_buffer_state( );

	/* We don't actually know whether we did this switch during
	 * EOF (yywrap()) processing, but the only time this flag
	 * is looked at is after yywrap() is called, so it's safe
	 * to go ahead and always set it.
	 */
	(yy_did_buffer_switch_on_eof) = 1;
}

static void yy_load_buffer_state  (void)
{
    	(yy_n_chars) = YY_CURRENT_BUFFER_LVALUE->yy_n_chars;
	(yytext_ptr) = (yy_c_buf_p) = YY_CURRENT_BUFFER_LVALUE->yy_buf_pos;
	yyin = YY_CURRENT_BUFFER_LVALUE->yy_input_file;
	(yy_hold_char) = *(yy_c_buf_p);
}

/** Allocate and initialize an input buffer state.
 * @param file A readable stream.
 * @param size The character buffer size in bytes. When in doubt, use @c YY_BUF_SIZE.
 * 
 * @return the allocated buffer state.
 */
    YY_BUFFER_STATE yy_create_buffer  (FILE * file, int  size )
{
	YY_BUFFER_STATE b;
    
	b = (YY_BUFFER_STATE) yyalloc(sizeof( struct yy_buffer_state )  );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_buf_size = (yy_size_t)size;

	/* yy_ch_buf has to be 2 characters longer than the size given because
	 * we need to put in 2 end-of-buffer characters.
	 */
	b->yy_ch_buf = (char *) yyalloc(b->yy_buf_size + 2  );
	if ( ! b->yy_ch_buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_is_our_buffer = 1;

	yy_init_buffer(b,file );

	return b;
}

/** Destroy the buffer.
 * @param b a buffer created with yy_create_buffer()
 * 
 */
    void yy_delete_buffer (YY_BUFFER_STATE  b )
{
    
	if ( ! b )
		return;

	if ( b == YY_CURRENT_BUFFER ) /* Not sure if we should pop here. */
		YY_CURRENT_BUFFER_LVALUE = (YY_BUFFER_STATE) 0;

	if ( b->yy_is_our_buffer )
		yyfree((void *) b->yy_ch_buf  );

	yyfree((void *) b  );
}

/* Initializes or reinitializes a buffer.
 * This function is sometimes called more than once on the same buffer,
 * such as during a yyrestart() or at EOF.
 */
    static void yy_init_buffer  (YY_BUFFER_STATE  b, FILE * file )

{
	int oerrno = errno;
    
	yy_flush_buffer(b );

	b->yy_input_file = file;
	b->yy_fill_buffer = 1;

    /* If b is the current buffer, then yy_init_buffer was _probably_
     * called from yyrestart() or through yy_get_next_buffer.
     * In that case, we don't want to reset the lineno or column.
     */
    if (b != YY_CURRENT_BUFFER){
        b->yy_bs_lineno = 1;
        b->yy_bs_column = 0;
    }

        b->yy_is_interactive = file ? (isatty( fileno(file) ) > 0) : 0;
    
	errno = oerrno;
}

/** Discard all buffered characters. On the next scan, YY_INPUT will be called.
 * @param b the buffer state to be flushed, usually @c YY_CURRENT_BUFFER.
 * 
 */
    void yy_flush_buffer (YY_BUFFER_STATE  b )
{
    	if ( ! b )
		return;

	b->yy_n_chars = 0;

	/* We always need two end-of-buffer characters.  The first causes
	 * a transition to the end-of-buffer state.  The second causes
	 * a jam in that state.
	 */
	b->yy_ch_buf[0] = YY_END_OF_BUFFER_CHAR;
	b->yy_ch_buf[1] = YY_END_OF_BUFFER_CHAR;

	b->yy_buf_pos = &b->yy_ch_buf[0];

	b->yy_at_bol = 1;
	b->yy_buffer_status = YY_BUFFER_NEW;

	if ( b == YY_CURRENT_BUFFER )
		yy_load_buffer_state( );
}

/** Pushes the new state onto the stack. The new state becomes
 *  the current state. This function will allocate the stack
 *  if necessary.
 *  @param new_buffer The new state.
 *  
 */
void yypush_buffer_state (YY_BUFFER_STATE new_buffer )
{
    	if (new_buffer == NULL)
		return;

	yyensure_buffer_stack();

	/* This block is copied from yy_switch_to_buffer. */
	if ( YY_CURRENT_BUFFER )
		{
		/* Flush out information for old buffer. */
		*(yy_c_buf_p) = (yy_hold_char);
		YY_CURRENT_BUFFER_LVALUE->yy_buf_pos = (yy_c_buf_p);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	/* Only push if top exists. Otherwise, replace top. */
	if (YY_CURRENT_BUFFER)
		(yy_buffer_stack_top)++;
	YY_CURRENT_BUFFER_LVALUE = new_buffer;

	/* copied from yy_switch_to_buffer. */
	yy_load_buffer_state( );
	(yy_did_buffer_switch_on_eof) = 1;
}

/** Removes and deletes the top of the stack, if present.
 *  The next element becomes the new top.
 *  
 */
void yypop_buffer_state (void)
{
    	if (!YY_CURRENT_BUFFER)
		return;

	yy_delete_buffer(YY_CURRENT_BUFFER );
	YY_CURRENT_BUFFER_LVALUE = NULL;
	if ((yy_buffer_stack_top) > 0)
		--(yy_buffer_stack_top);

	if (YY_CURRENT_BUFFER) {
		yy_load_buffer_state( );
		(yy_did_buffer_switch_on_eof) = 1;
	}
}

/* Allocates the stack if it does not exist.
 *  Guarantees space for at least one push.
 */
static void yyensure_buffer_stack (void)
{
	yy_size_t num_to_alloc;
    
	if (!(yy_buffer_stack)) {

		/* First allocation is just for 2 elements, since we don't know if this
		 * scanner will even need a stack. We use 2 instead of 1 to avoid an
		 * immediate realloc on the next call.
         */
		num_to_alloc = 1; /* After all that talk, this was set to 1 anyways... */
		(yy_buffer_stack) = (struct yy_buffer_state**)yyalloc
								(num_to_alloc * sizeof(struct yy_buffer_state*)
								);
		if ( ! (yy_buffer_stack) )
			YY_FATAL_ERROR( "out of dynamic memory in yyensure_buffer_stack()" );
								  
		memset((yy_buffer_stack), 0, num_to_alloc * sizeof(struct yy_buffer_state*));
				
		(yy_buffer_stack_max) = num_to_alloc;
		(yy_buffer_stack_top) = 0;
		return;
	}

	if ((yy_buffer_stack_top) >= ((yy_buffer_stack_max)) - 1){

		/* Increase the buffer to prepare for a possible push. */
		yy_size_t grow_size = 8 /* arbitrary grow size */;

		num_to_alloc = (yy_buffer_stack_max) + grow_size;
		(yy_buffer_stack) = (struct yy_buffer_state**)yyrealloc
								((yy_buffer_stack),
								num_to_alloc * sizeof(struct yy_buffer_state*)
								);
		if ( ! (yy_buffer_stack) )
			YY_FATAL_ERROR( "out of dynamic memory in yyensure_buffer_stack()" );

		/* zero only the new slots.*/
		memset((yy_buffer_stack) + (yy_buffer_stack_max), 0, grow_size * sizeof(struct yy_buffer_state*));
		(yy_buffer_stack_max) = num_to_alloc;
	}
}

/** Setup the input buffer state to scan directly from a user-specified character buffer.
 * @param base the character buffer
 * @param size the size in bytes of the character buffer
 * 
 * @return the newly allocated buffer state object. 
 */
YY_BUFFER_STATE yy_scan_buffer  (char * base, yy_size_t  size )
{
	YY_BUFFER_STATE b;
    
	if ( size < 2 ||
	     base[size-2] != YY_END_OF_BUFFER_CHAR ||
	     base[size-1] != YY_END_OF_BUFFER_CHAR )
		/* They forgot to leave room for the EOB's. */
		return 0;

	b = (YY_BUFFER_STATE) yyalloc(sizeof( struct yy_buffer_state )  );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_scan_buffer()" );

	b->yy_buf_size = size - 2;	/* "- 2" to take care of EOB's */
	b->yy_buf_pos = b->yy_ch_buf = base;
	b->yy_is_our_buffer = 0;
	b->yy_input_file = 0;
	b->yy_n_chars = b->yy_buf_size;
	b->yy_is_interactive = 0;
	b->yy_at_bol = 1;
	b->yy_fill_buffer = 0;
	b->yy_buffer_status = YY_BUFFER_NEW;

	yy_switch_to_buffer(b  );

	return b;
}

/** Setup the input buffer state to scan a string. The next call to yylex() will
 * scan from a @e copy of @a str.
 * @param yystr a NUL-terminated string to scan
 * 
 * @return the newly allocated buffer state object.
 * @note If you want to scan bytes that may contain NUL values, then use
 *       yy_scan_bytes() instead.
 */
YY_BUFFER_STATE yy_scan_string (yyconst char * yystr )
{
    
	return yy_scan_bytes(yystr,strlen(yystr) );
}

/** Setup the input buffer state to scan the given bytes. The next call to yylex() will
 * scan from a @e copy of @a bytes.
 * @param yybytes the byte buffer to scan
 * @param _yybytes_len the number of bytes in the buffer pointed to by @a bytes.
 * 
 * @return the newly allocated buffer state object.
 */
YY_BUFFER_STATE yy_scan_bytes  (yyconst char * yybytes, yy_size_t  _yybytes_len )
{
	YY_BUFFER_STATE b;
	char *buf;
	yy_size_t n;
	yy_size_t i;
    
	/* Get memory for full buffer, including space for trailing EOB's. */
	n = _yybytes_len + 2;
	buf = (char *) yyalloc(n  );
	if ( ! buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_scan_bytes()" );

	for ( i = 0; i < _yybytes_len; ++i )
		buf[i] = yybytes[i];

	buf[_yybytes_len] = buf[_yybytes_len+1] = YY_END_OF_BUFFER_CHAR;

	b = yy_scan_buffer(buf,n );
	if ( ! b )
		YY_FATAL_ERROR( "bad buffer in yy_scan_bytes()" );

	/* It's okay to grow etc. this buffer, and we should throw it
	 * away when we're done.
	 */
	b->yy_is_our_buffer = 1;

	return b;
}

#ifndef YY_EXIT_FAILURE
#define YY_EXIT_FAILURE 2
#endif

static void yy_fatal_error (yyconst char* msg )
{
			(void) fprintf( stderr, "%s\n", msg );
	exit( YY_EXIT_FAILURE );
}

/* Redefine yyless() so it works in section 3 code. */

#undef yyless
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
        int yyless_macro_arg = (n); \
        YY_LESS_LINENO(yyless_macro_arg);\
		yytext[yyleng] = (yy_hold_char); \
		(yy_c_buf_p) = yytext + yyless_macro_arg; \
		(yy_hold_char) = *(yy_c_buf_p); \
		*(yy_c_buf_p) = '\0'; \
		yyleng = yyless_macro_arg; \
		} \
	while ( 0 )

/* Accessor  methods (get/set functions) to struct members. */

/** Get the current line number.
 * 
 */
int yyget_lineno  (void)
{
        
    return yylineno;
}

/** Get the input stream.
 * 
 */
FILE *yyget_in  (void)
{
        return yyin;
}

/** Get the output stream.
 * 
 */
FILE *yyget_out  (void)
{
        return yyout;
}

/** Get the length of the current token.
 * 
 */
yy_size_t yyget_leng  (void)
{
        return yyleng;
}

/** Get the current token.
 * 
 */

char *yyget_text  (void)
{
        return yytext;
}

/** Set the current line number.
 * @param _line_number line number
 * 
 */
void yyset_lineno (int  _line_number )
{
    
    yylineno = _line_number;
}

/** Set the input stream. This does not discard the current
 * input buffer.
 * @param _in_str A readable stream.
 * 
 * @see yy_switch_to_buffer
 */
void yyset_in (FILE *  _in_str )
{
        yyin = _in_str ;
}

void yyset_out (FILE *  _out_str )
{
        yyout = _out_str ;
}

int yyget_debug  (void)
{
        return yy_flex_debug;
}

void yyset_debug (int  _bdebug )
{
        yy_flex_debug = _bdebug ;
}

static int yy_init_globals (void)
{
        /* Initialization is the same as for the non-reentrant scanner.
     * This function is called from yylex_destroy(), so don't allocate here.
     */

    (yy_buffer_stack) = 0;
    (yy_buffer_stack_top) = 0;
    (yy_buffer_stack_max) = 0;
    (yy_c_buf_p) = (char *) 0;
    (yy_init) = 0;
    (yy_start) = 0;

/* Defined in main.c */
#ifdef YY_STDINIT
    yyin = stdin;
    yyout = stdout;
#else
    yyin = (FILE *) 0;
    yyout = (FILE *) 0;
#endif

    /* For future reference: Set errno on error, since we are called by
     * yylex_init()
     */
    return 0;
}

/* yylex_destroy is for both reentrant and non-reentrant scanners. */
int yylex_destroy  (void)
{
    
    /* Pop the buffer stack, destroying each element. */
	while(YY_CURRENT_BUFFER){
		yy_delete_buffer(YY_CURRENT_BUFFER  );
		YY_CURRENT_BUFFER_LVALUE = NULL;
		yypop_buffer_state();
	}

	/* Destroy the stack itself. */
	yyfree((yy_buffer_stack) );
	(yy_buffer_stack) = NULL;

    /* Reset the globals. This is important in a non-reentrant scanner so the next time
     * yylex() is called, initialization will occur. */
    yy_init_globals( );

    return 0;
}

/*
 * Internal utility routines.
 */

#ifndef yytext_ptr
static void yy_flex_strncpy (char* s1, yyconst char * s2, int n )
{
		
	int i;
	for ( i = 0; i < n; ++i )
		s1[i] = s2[i];
}
#endif

#ifdef YY_NEED_STRLEN
static int yy_flex_strlen (yyconst char * s )
{
	int n;
	for ( n = 0; s[n]; ++n )
		;

	return n;
}
#endif

void *yyalloc (yy_size_t  size )
{
			return (void *) malloc( size );
}

void *yyrealloc  (void * ptr, yy_size_t  size )
{
		
	/* The cast to (char *) in the following accommodates both
	 * implementations that use char* generic pointers, and those
	 * that use void* generic pointers.  It works with the latter
	 * because both ANSI C and C++ allow castless assignment from
	 * any pointer type to void*, and deal with argument conversions
	 * as though doing an assignment.
	 */
	return (void *) realloc( (char *) ptr, size );
}

void yyfree (void * ptr )
{
			free( (char *) ptr );	/* see yyrealloc() for (char *) cast */
}

#define YYTABLES_NAME "yytables"

#line 272 "clex.l"



void lexerr(char *s)
{
	errors++;

	fprintf(stderr, "%s: lexical error", s);

	fprintf(stderr, ", C++ token \"%s\" is not legal in 120++, file: %s line: %d\n", yytext, file_name, line_num);
  exit(1);
}

/*
 * Return 1 if done, 0 if yyin points at more input
 */
int yywrap()
{
   if(yybuffer_state_counter == 0)
   {
      line_num = 1;
      clear_typename_table();
      //clear_sysinclude_flags();

      return 1;
   }
   else
   {
      fclose(yyin);
      /* pop the buffer state */
      yypop_buffer_state();
      yybuffer_state_counter--;
      
      /* create a fileinfo struct to get contents from the top of the include_stack */
      struct fileinfo *info = (struct fileinfo*)malloc(sizeof(struct fileinfo));
      info = include_stack[top];
      top--;

      file_name = info->file_name;
      line_num = info->line_num;

      /* make sure to free the fileinfo struct because we don't need it anymore */
      info = NULL;
      free(info);
      return 0;
   }
}

void generate_token(int token_num)
{
   /* Create a new struct token and fill in the token information */
   struct token *t = (struct token*)malloc(sizeof(struct token));
   t->dvalflag = 0;
   t->svalflag = 0;
   t->ivalflag = 0;   

   t->category = token_num;
   t->text = strdup(yytext);
   t->lineno = line_num; 
   t->filename = strdup(file_name);

   /* Store svals/ivals/dvals depending on what type token was found */
   switch(token_num)
   {
      case STRING :
      case CHARACTER :
         t->sval = strdup(sval);
         t->svalflag = 1;
         break;
      case INTEGER :
         t->ival = ival;
         t->ivalflag = 1;
         break;
      case FLOATING :
         t->dval = dval;
         t->dvalflag = 1;
         break;
      default :
         break;
   }
   
   /* Give the token to yytoken so main() can use it */
   yytoken = t;   
}

struct tree *leaf_node(int token_num)
{
   struct tree *new_leafnode = (struct tree*)malloc(sizeof(struct tree));
   new_leafnode->prodrule = token_num;
   new_leafnode->nkids = 0;    //no kids
   new_leafnode->leaf = yytoken;
   return new_leafnode;
}


void handle_user_include()
{
   /* Check if we have too many nested includes */
   top++;
   if(top >= MAX_INCLUDE_DEPTH)
   {
      printf("error: includes nested too deeply\n");
      exit(1);
   }
 

   /* Get the user included file name */
   char *fname = strchr(yytext, '\"')+1;
   fname[strlen(fname)-1] = '\0';
   fname = strdup(fname);

   FILE *input_file = fopen(fname, "r");
   if(!input_file)
   {
      fprintf(stderr, "Unable to open include file: %s\n", fname);
      perror("");
      exit(1);
   }

   
   /* Save the current file information in a fileinfo struct */
   struct fileinfo *fi = (struct fileinfo*)malloc(sizeof(struct fileinfo));
   fi->line_num = line_num;
   fi->file_name = file_name;

   
   /* Add the saved file information to the top of the include_stack */
   include_stack[top] = (struct fileinfo*)malloc(sizeof(struct fileinfo));
   include_stack[top] = fi;

   /* Change the file name and reset the number of lines */
   file_name = fname;
   line_num = 1;


   /* Push flex's internal buffer state */
   yypush_buffer_state(yy_create_buffer(input_file,YY_BUF_SIZE));
   yybuffer_state_counter++;   
}



/* 
 * Converts string to sval by removing qutoes
 * and unnecessary escaped characters
*/
void string_to_sval(char *text)
{
   /* Remove quotes from string */
   char *temp_sval = strdup(text);
   temp_sval = strchr(temp_sval, '\"')+1;
   temp_sval[strlen(temp_sval) - 1] = '\0';
   
   
   /* Remove unnecessary substrings from string */
   remove_substring(temp_sval, "\\n");
   remove_substring(temp_sval, "\\t");
   remove_substring(temp_sval, "\\0");  
   remove_substring(temp_sval, "\\'");
   remove_substring(temp_sval, "\\\\");
   remove_substring(temp_sval, "\\\"");
     
   
   /* Duplicate string to sval, free temp_sval */
   sval = strdup(temp_sval);
   temp_sval = NULL;
   free(temp_sval);
}



/* 
 * Convert single characters to sval 
*/
void char_to_sval(char *text)
{
   /* Remove apostrophes from characters */
   char *char_temp = strdup(text);
   char_temp = strchr(char_temp, '\'')+1;
   char_temp[strlen(char_temp)-1] = '\0';

   
   /* Duplicate character to sval, free char_temp */
   sval = strdup(char_temp);
   char_temp = NULL;
   free(char_temp);
}

void remove_substring(char *s, char *s_remove)
{
   /* 
      Found an easy way to remove substrings from a string online and I modified it a little
      https://stackoverflow.com/questions/4833347/removing-substring-from-a-string
   */

   char *temp_str = NULL;
   int rlen = strlen(s_remove);
   
   while((temp_str = strstr(s, s_remove)))
   {
      //int tlen = strlen(temp_str);
      
      if(strcmp(s_remove, "\\'") == 0 || strcmp(s_remove, "\\\\") == 0 || strcmp(s_remove, "\\\"") == 0)
         memmove(temp_str, temp_str + (rlen - 1), 1 + strlen(temp_str + (rlen - 1)));
      

      /* If we see \n \t or \0, remove the entire escaped character and replace with control character */
      else if(strcmp(s_remove, "\\n") == 0)
      {
         memmove(temp_str, temp_str + (rlen - 1), 1 + strlen(temp_str + (rlen - 1)));
         *temp_str = '\012';
      }
      else if(strcmp(s_remove, "\\t") == 0)
      {
         memmove(temp_str, temp_str + (rlen - 1), 1 + strlen(temp_str + (rlen - 1)));
         *temp_str = '\011';
      }
      else if(strcmp(s_remove, "\\0") == 0)
      {
         memmove(temp_str, temp_str + rlen, 1 + strlen(temp_str + rlen));
         *temp_str = '\000';
      }
      
      
      /* Otherwise, just remove the entire string */
      else
         memmove(temp_str, temp_str + rlen, 1 + strlen(temp_str + rlen));   
   }

   temp_str = NULL;
   free(temp_str);
}



/*
 * Type name table.
*/
int typenametable_lookup(char *s)
{
   struct typenametable_entry *tmp = head;
   while (tmp != NULL) {
      if (strcmp(s, tmp->name) == 0)
        return tmp->category;
      tmp = tmp->next;
   }
   return IDENTIFIER;
}

int typenametable_insert(char *s, int cat)
{
   struct typenametable_entry *tmp = head;
   while (tmp) {
      if (!strcmp(s, tmp->name)) {
         printf("warning: %s is already in the typename table as a %d\n", s, tmp->category);
         return tmp->category;
         }
      tmp = tmp->next;
   }
   tmp = calloc(1, sizeof (struct typenametable_entry));
   if(!tmp) { fprintf(stderr, "tnti out of memory\n"); return -1; }
   tmp->name = strdup(s);
   tmp->category = cat;
   tmp->next = head;
   head = tmp;
   return 0;
}

int check_identifier(char *s)
{
   return typenametable_lookup(s);
}

void clear_typename_table()
{
   struct typenametable_entry *curr = head;
   struct typenametable_entry *next;
   while(curr != NULL)
   {
      next = curr->next;
      curr->next = NULL;
      free(curr);
      curr = next;
   }

   head = NULL;  
}

void clear_sysinclude_flags()
{
   included_std = 0;
   included_iostream = 0;
   included_string = 0;
   included_ctime = 0;
   included_cstdlib = 0;
   included_cmath = 0;
   included_fstream = 0; 
}

